In [2]:
# import numpy
import numpy as np
# numpy array - need to pass in python list
arr = np.array([1,2,3,4,5])
# display output
arr

array([1, 2, 3, 4, 5])

In [3]:
prices = [10,20,30,40]
prices_array = np.array(prices)
prices_array

array([10, 20, 30, 40])

In [4]:
names = ['John', 'Matt', 'Rob']
names_array = np.array(names)
names_array

array(['John', 'Matt', 'Rob'], dtype='<U4')

In [5]:
names_array[0]

'John'

In [6]:
multi_array = np.array([[1,2,3],[4,5,6]])
multi_array

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
multi_array[1][2]

6

In [10]:
multi_array.ndim

2

In [11]:
names_array.ndim

1

In [13]:
names_array.dtype

dtype('<U4')

In [1]:
auto_array = np.zeros(10)
auto_array

NameError: name 'np' is not defined

In [2]:
import numpy as np
auto_array = np.zeros(10)
auto_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
auto_array.dtype

dtype('float64')

In [4]:
auto_array.astype(np.int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
auto_array = auto_array.astype(np.int64)

In [7]:
auto_array = auto_array.astype(np.int64)
auto_array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
array = np.array([1,2,3,4], dtype=np.float64)
array

array([1., 2., 3., 4.])

In [9]:
array = np.array([1,2,3,4], dtype='i')
array

array([1, 2, 3, 4], dtype=int32)

In [10]:
array.dtype

dtype('int32')

In [11]:
array = np.array([1,2,3,4], dtype='b')
array
array.dtype

dtype('int8')

In [12]:
array = np.array([1,2,3,4], dtype='u')
array
array.dtype

TypeError: data type 'u' not understood

In [13]:
array = np.array([1,2,3,4], dtype='f')
array
array.dtype

dtype('float32')

In [14]:
array = np.array([1,2,3,4], dtype='c')
array
array.dtype

dtype('S1')

In [15]:
array = np.array([1,2,3,4], dtype='m')
array
array.dtype

dtype('<m8')

In [16]:
array = np.array([1,2,3,4], dtype='M')
array
array.dtype

ValueError: Converting an integer to a NumPy datetime requires a specified unit

In [17]:
array = np.array([1,2,3,4], dtype='O')
array
array.dtype

dtype('O')

In [18]:
array = np.array([1,2,3,4], dtype='S')
array
array.dtype

dtype('S1')

In [19]:
array = np.array([1,2,3,4], dtype='U')
array
array.dtype

dtype('<U1')

In [20]:
array = np.array([1,2,3,4], dtype='V')
array
array.dtype

TypeError: A bytes-like object is required, not 'int'

In [21]:
array = np.array([1,2,3,4], dtype='S')
array

array([b'1', b'2', b'3', b'4'], dtype='|S1')

In [22]:
array = np.array([1,2,3,4], dtype=np.float64)
array
array.dtype

dtype('float64')

In [23]:
listA = [[1,2,3], [4,5,6]]
listB = [[7,8,9], [10,11,12]]
arrayA = np.array(listA)
arrayB = np.array(listB)
arrayA

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
arrayB

array([[ 7,  8,  9],
       [10, 11, 12]])

In [25]:
arrayA + arrayB

array([[ 8, 10, 12],
       [14, 16, 18]])

In [26]:
arrayB - arrayA

array([[6, 6, 6],
       [6, 6, 6]])

In [27]:
arrayA * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [28]:
arrayB / 10

array([[0.7, 0.8, 0.9],
       [1. , 1.1, 1.2]])

In [29]:
arrayA * arrayB

array([[ 7, 16, 27],
       [40, 55, 72]])

In [30]:
arrayB / arrayA

array([[7. , 4. , 3. ],
       [2.5, 2.2, 2. ]])

In [31]:
arrayB ** 2

array([[ 49,  64,  81],
       [100, 121, 144]])

In [32]:
arrayA > arrayB

array([[False, False, False],
       [False, False, False]])

In [33]:
arrayA < arrayB

array([[ True,  True,  True],
       [ True,  True,  True]])

In [34]:
import numpy as np
arr = np.array([10,20,30,40,50])
arr

array([10, 20, 30, 40, 50])

In [35]:
arr[0]

10

In [36]:
arr[3]

40

In [37]:
arr = np.array([1,2,3],[4,5,6])
arr

TypeError: Field elements must be 2- or 3-tuples, got '4'

In [38]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
arr[1][2]

6

In [40]:
arr[1,2]

6

In [41]:
arr = np.array([10,20,30,40,50,60,70])
arr

array([10, 20, 30, 40, 50, 60, 70])

In [42]:
arr[1:5]

array([20, 30, 40, 50])

In [44]:
arrayM = np.array([[1,2,3],[4,5,6],[7,8,9]])
arrayM

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
arrayM[1:2]

array([[4, 5, 6]])

In [46]:
arrayM[1:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [47]:
arrayM[1:3, 1:3]

array([[5, 6],
       [8, 9]])

In [48]:
arrayM[0:2, 0:2]

array([[1, 2],
       [4, 5]])

In [49]:
arrayM[:2, :2]

array([[1, 2],
       [4, 5]])

In [50]:
arrayM = np.array([[1,2,3],[4,5,6],[7,8,9]])
arrayM

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
arrayM[[0, 0, 2, 2],[0, 2, 0, 2]]

array([1, 3, 7, 9])

In [52]:
arrayM

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
arrayM[arrayM>5]

array([6, 7, 8, 9])

In [54]:
arrayM[arrayM < 7]

array([1, 2, 3, 4, 5, 6])

In [1]:
import numpy as np

In [2]:
arrayA = np.array([[1,2,3],[4,5,6],[7,8,9]])
arrayB = np.array([1,2,3])
arrayA
arrayB

array([1, 2, 3])

In [3]:
arrayA

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
arrayA + arrayB

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [6]:
from pandas import Series
s = Series([1,3,5,7,9])
s

0    1
1    3
2    5
3    7
4    9
dtype: int64

In [7]:
s[3]

7

In [8]:
s.values

array([1, 3, 5, 7, 9])

In [9]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [11]:
s = Series([100,200,300], index=[5,2,3])
s

5    100
2    200
3    300
dtype: int64

In [12]:
s = Series([100,200,300], index=['a','b','c'])
s

a    100
b    200
c    300
dtype: int64

In [13]:
s['c']

300

In [14]:
s = Series({'a':100, 'b':700, 'c':1400})
s

a     100
b     700
c    1400
dtype: int64

In [1]:
import numpy as np


In [3]:
from pandas import DataFrame
people = {'name':['Jim', 'Rob', 'Tom'], 'age':[22,44,55], 'location':['US', 'UK', 'AUS']}
frame = DataFrame(people, columns=['name', 'location', 'age'])
frame

name location  age
0  Jim       US   22
1  Rob       UK   44
2  Tom      AUS   55

In [4]:
frame['location']

0     US
1     UK
2    AUS
Name: location, dtype: object

In [5]:
frame.location

0     US
1     UK
2    AUS
Name: location, dtype: object

In [6]:
frame.loc[1]

name        Rob
location     UK
age          44
Name: 1, dtype: object