In [2]:
# import numpy
import numpy as np
# numpy array - need to pass in python list
arr = np.array([1,2,3,4,5])
# display output
arr

array([1, 2, 3, 4, 5])

In [3]:
prices = [10,20,30,40]
prices_array = np.array(prices)
prices_array

array([10, 20, 30, 40])

In [4]:
names = ['John', 'Matt', 'Rob']
names_array = np.array(names)
names_array

array(['John', 'Matt', 'Rob'], dtype='<U4')

In [5]:
names_array[0]

'John'

In [6]:
multi_array = np.array([[1,2,3],[4,5,6]])
multi_array

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
multi_array[1][2]

6

In [10]:
multi_array.ndim

2

In [11]:
names_array.ndim

1

In [13]:
names_array.dtype

dtype('<U4')

In [1]:
auto_array = np.zeros(10)
auto_array

NameError: name 'np' is not defined

In [2]:
import numpy as np
auto_array = np.zeros(10)
auto_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
auto_array.dtype

dtype('float64')

In [4]:
auto_array.astype(np.int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
auto_array = auto_array.astype(np.int64)

In [7]:
auto_array = auto_array.astype(np.int64)
auto_array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
array = np.array([1,2,3,4], dtype=np.float64)
array

array([1., 2., 3., 4.])

In [9]:
array = np.array([1,2,3,4], dtype='i')
array

array([1, 2, 3, 4], dtype=int32)

In [10]:
array.dtype

dtype('int32')

In [11]:
array = np.array([1,2,3,4], dtype='b')
array
array.dtype

dtype('int8')

In [12]:
array = np.array([1,2,3,4], dtype='u')
array
array.dtype

TypeError: data type 'u' not understood

In [13]:
array = np.array([1,2,3,4], dtype='f')
array
array.dtype

dtype('float32')

In [14]:
array = np.array([1,2,3,4], dtype='c')
array
array.dtype

dtype('S1')

In [15]:
array = np.array([1,2,3,4], dtype='m')
array
array.dtype

dtype('<m8')

In [16]:
array = np.array([1,2,3,4], dtype='M')
array
array.dtype

ValueError: Converting an integer to a NumPy datetime requires a specified unit

In [17]:
array = np.array([1,2,3,4], dtype='O')
array
array.dtype

dtype('O')

In [18]:
array = np.array([1,2,3,4], dtype='S')
array
array.dtype

dtype('S1')

In [19]:
array = np.array([1,2,3,4], dtype='U')
array
array.dtype

dtype('<U1')

In [20]:
array = np.array([1,2,3,4], dtype='V')
array
array.dtype

TypeError: A bytes-like object is required, not 'int'

In [21]:
array = np.array([1,2,3,4], dtype='S')
array

array([b'1', b'2', b'3', b'4'], dtype='|S1')

In [22]:
array = np.array([1,2,3,4], dtype=np.float64)
array
array.dtype

dtype('float64')

In [23]:
listA = [[1,2,3], [4,5,6]]
listB = [[7,8,9], [10,11,12]]
arrayA = np.array(listA)
arrayB = np.array(listB)
arrayA

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
arrayB

array([[ 7,  8,  9],
       [10, 11, 12]])

In [25]:
arrayA + arrayB

array([[ 8, 10, 12],
       [14, 16, 18]])

In [26]:
arrayB - arrayA

array([[6, 6, 6],
       [6, 6, 6]])

In [27]:
arrayA * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [28]:
arrayB / 10

array([[0.7, 0.8, 0.9],
       [1. , 1.1, 1.2]])

In [29]:
arrayA * arrayB

array([[ 7, 16, 27],
       [40, 55, 72]])

In [30]:
arrayB / arrayA

array([[7. , 4. , 3. ],
       [2.5, 2.2, 2. ]])

In [31]:
arrayB ** 2

array([[ 49,  64,  81],
       [100, 121, 144]])

In [32]:
arrayA > arrayB

array([[False, False, False],
       [False, False, False]])

In [33]:
arrayA < arrayB

array([[ True,  True,  True],
       [ True,  True,  True]])

In [34]:
import numpy as np
arr = np.array([10,20,30,40,50])
arr

array([10, 20, 30, 40, 50])

In [35]:
arr[0]

10

In [36]:
arr[3]

40

In [37]:
arr = np.array([1,2,3],[4,5,6])
arr

TypeError: Field elements must be 2- or 3-tuples, got '4'

In [38]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
arr[1][2]

6

In [40]:
arr[1,2]

6

In [41]:
arr = np.array([10,20,30,40,50,60,70])
arr

array([10, 20, 30, 40, 50, 60, 70])

In [42]:
arr[1:5]

array([20, 30, 40, 50])

In [44]:
arrayM = np.array([[1,2,3],[4,5,6],[7,8,9]])
arrayM

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
arrayM[1:2]

array([[4, 5, 6]])

In [46]:
arrayM[1:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [47]:
arrayM[1:3, 1:3]

array([[5, 6],
       [8, 9]])

In [48]:
arrayM[0:2, 0:2]

array([[1, 2],
       [4, 5]])

In [49]:
arrayM[:2, :2]

array([[1, 2],
       [4, 5]])

In [50]:
arrayM = np.array([[1,2,3],[4,5,6],[7,8,9]])
arrayM

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
arrayM[[0, 0, 2, 2],[0, 2, 0, 2]]

array([1, 3, 7, 9])

In [52]:
arrayM

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
arrayM[arrayM>5]

array([6, 7, 8, 9])

In [54]:
arrayM[arrayM < 7]

array([1, 2, 3, 4, 5, 6])

In [1]:
import numpy as np

In [2]:
arrayA = np.array([[1,2,3],[4,5,6],[7,8,9]])
arrayB = np.array([1,2,3])
arrayA
arrayB

array([1, 2, 3])

In [3]:
arrayA

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
arrayA + arrayB

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [6]:
from pandas import Series
s = Series([1,3,5,7,9])
s

0    1
1    3
2    5
3    7
4    9
dtype: int64

In [7]:
s[3]

7

In [8]:
s.values

array([1, 3, 5, 7, 9])

In [9]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [11]:
s = Series([100,200,300], index=[5,2,3])
s

5    100
2    200
3    300
dtype: int64

In [12]:
s = Series([100,200,300], index=['a','b','c'])
s

a    100
b    200
c    300
dtype: int64

In [13]:
s['c']

300

In [14]:
s = Series({'a':100, 'b':700, 'c':1400})
s

a     100
b     700
c    1400
dtype: int64

In [1]:
import numpy as np


In [3]:
from pandas import DataFrame
people = {'name':['Jim', 'Rob', 'Tom'], 'age':[22,44,55], 'location':['US', 'UK', 'AUS']}
frame = DataFrame(people, columns=['name', 'location', 'age'])
frame

name location  age
0  Jim       US   22
1  Rob       UK   44
2  Tom      AUS   55

In [4]:
frame['location']

0     US
1     UK
2    AUS
Name: location, dtype: object

In [5]:
frame.location

0     US
1     UK
2    AUS
Name: location, dtype: object

In [6]:
frame.loc[1]

name        Rob
location     UK
age          44
Name: 1, dtype: object

In [7]:
frame

name location  age
0  Jim       US   22
1  Rob       UK   44
2  Tom      AUS   55

In [9]:
frame

name location  age
0  Jim       US   22
1  Rob       UK   44
2  Tom      AUS   55

In [10]:
from pandas import DataFrame
people = {'name':['Jim', 'Rob', 'Tom'], 'age':[22,44,55], 'location':['US', 'UK', 'AUS']}
frame = DataFrame(people, columns=['name', 'location', 'age', 'salary'])
frame

name location  age salary
0  Jim       US   22    NaN
1  Rob       UK   44    NaN
2  Tom      AUS   55    NaN

In [11]:
frame.salary = 5000
frame

name location  age  salary
0  Jim       US   22    5000
1  Rob       UK   44    5000
2  Tom      AUS   55    5000

In [15]:
from pandas import Series
salaries = Series([1000,2000,3000])
frame.salary = salaries

In [16]:
from pandas import DataFrame
from pandas import Series
people = {'name':['Jim', 'Rob', 'Tom'], 'age':[22,44,55], 'location':['US', 'UK', 'AUS']}
frame = DataFrame(people, columns=['name', 'location', 'age', 'salary'])
salaries = Series([1000,2000,3000])
frame.salary = salaries
frame

name location  age  salary
0  Jim       US   22    1000
1  Rob       UK   44    2000
2  Tom      AUS   55    3000

In [17]:
del frame['salary']

In [18]:
frame

name location  age
0  Jim       US   22
1  Rob       UK   44
2  Tom      AUS   55

In [1]:
import numpy as np
from pandas import DataFrame
from pandas import Series

In [2]:
s = Series([10,20,30,40,50], index=['c','a','d','b','e'])

In [3]:
s

c    10
a    20
d    30
b    40
e    50
dtype: int64

In [4]:
s = s.reindex(['a','b','c','d','e'])
s

a    20
b    40
c    10
d    30
e    50
dtype: int64

In [8]:
d = DataFrame(np.arange(9).reshape((3,3)), index=['c','a','b'], columns=['apple','mango','banana'])
d

apple  mango  banana
c      0      1       2
a      3      4       5
b      6      7       8

In [9]:
d.reindex(['a','b','c'])

apple  mango  banana
a      3      4       5
b      6      7       8
c      0      1       2

In [15]:
d = d.reindex(['a','b','c'])
d.reindex(columns=['mango','banana','apple'])
d

apple  mango  banana
a      3      4       5
b      6      7       8
c      0      1       2

In [16]:
s1 = Series([1,2,3,4,5], index=['a','b','c','d','e'])
s2 = Series([1,2,3,4,5,6,7], index=['a','b','c','d','e','f','g'])
s1

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [17]:
s2

a    1
b    2
c    3
d    4
e    5
f    6
g    7
dtype: int64

In [18]:
s1 + s2

a     2.0
b     4.0
c     6.0
d     8.0
e    10.0
f     NaN
g     NaN
dtype: float64

In [20]:
s1.add(s2,fill_value=0)

a     2.0
b     4.0
c     6.0
d     8.0
e    10.0
f     6.0
g     7.0
dtype: float64

In [21]:
d1 = DataFrame(np.arange(12).reshape(3,4),columns=['a','b','c','d'])
d2 = DataFrame(np.arange(16).reshape(4,4),columns=['a','b','c','d'])
d1

a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [22]:
d2

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [23]:
d1.add(d2,fill_value=0)

a     b     c     d
0   0.0   2.0   4.0   6.0
1   8.0  10.0  12.0  14.0
2  16.0  18.0  20.0  22.0
3  12.0  13.0  14.0  15.0

In [25]:
s = Series([1,2,3,4])
d = DataFrame(np.arange(8).reshape(2,4))
s

0    1
1    2
2    3
3    4
dtype: int64

In [26]:
d

0  1  2  3
0  0  1  2  3
1  4  5  6  7

In [27]:
s+d

0  1  2   3
0  1  3  5   7
1  5  7  9  11

In [29]:
d = DataFrame(np.arange(16).reshape(4,4))
d

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [30]:
f = lambda x: x+10
d.apply(f)

0   1   2   3
0  10  11  12  13
1  14  15  16  17
2  18  19  20  21
3  22  23  24  25

In [31]:
f2 = lambda x: x*x
d.apply(f2)

0    1    2    3
0    0    1    4    9
1   16   25   36   49
2   64   81  100  121
3  144  169  196  225

In [1]:
import numpy as np
from pandas import DataFrame
from pandas import Series

In [2]:
s = Series([1,2,3,4], index=['d','c','b','a'])

In [3]:
s

d    1
c    2
b    3
a    4
dtype: int64

In [4]:
s.sort_index()

a    4
b    3
c    2
d    1
dtype: int64

In [6]:
d = DataFrame(np.arange(16).reshape(4,4), index=[3,1,4,2], columns=['d','c','b','a'])
d

d   c   b   a
3   0   1   2   3
1   4   5   6   7
4   8   9  10  11
2  12  13  14  15

In [9]:
d.sort_index(axis=1, ascending=False)

d   c   b   a
3   0   1   2   3
1   4   5   6   7
4   8   9  10  11
2  12  13  14  15

In [10]:
prices = Series([300,200,900,500])
prices

0    300
1    200
2    900
3    500
dtype: int64

In [11]:
prices.sort_values()

1    200
0    300
3    500
2    900
dtype: int64

In [12]:
products = DataFrame({'name':['phone','laptop','tablet'],'price':[200,300, 100]})
products

name  price
0   phone    200
1  laptop    300
2  tablet    100

In [14]:
products.sort_values(by='price',ascending=False)

name  price
1  laptop    300
0   phone    200
2  tablet    100

In [16]:
s = Series([1,2,3,4,5], index=['a','b','c','d','a'])
s

a    1
b    2
c    3
d    4
a    5
dtype: int64

In [17]:
s.index.is_unique

False

In [18]:
products = DataFrame({'name':['phone','laptop','tablet'],'price':[200,300, 100]})
products

name  price
0   phone    200
1  laptop    300
2  tablet    100

In [19]:
products.sum()

name     phonelaptoptablet
price                  600
dtype: object

In [20]:
products.count()

name     3
price    3
dtype: int64

In [21]:
products.describe()

price
count    3.0
mean   200.0
std    100.0
min    100.0
25%    150.0
50%    200.0
75%    250.0
max    300.0

In [22]:
s = Series([1,2,3,np.nan,np.nan,5])
s

0    1.0
1    2.0
2    3.0
3    NaN
4    NaN
5    5.0
dtype: float64

In [23]:
s.dropna()

0    1.0
1    2.0
2    3.0
5    5.0
dtype: float64

In [24]:
data = DataFrame([[1,2,3],[np.nan,np.nan,np.nan],[2,np.nan,4],[np.nan,3,np.nan]])
data

0    1    2
0  1.0  2.0  3.0
1  NaN  NaN  NaN
2  2.0  NaN  4.0
3  NaN  3.0  NaN

In [28]:
data.dropna(how='all',axis=1)

0    1    2
0  1.0  2.0  3.0
1  NaN  NaN  NaN
2  2.0  NaN  4.0
3  NaN  3.0  NaN

In [29]:
data[3]=np.nan

In [30]:
data

0    1    2   3
0  1.0  2.0  3.0 NaN
1  NaN  NaN  NaN NaN
2  2.0  NaN  4.0 NaN
3  NaN  3.0  NaN NaN

In [31]:
data.dropna(how='all',axis=1)

0    1    2
0  1.0  2.0  3.0
1  NaN  NaN  NaN
2  2.0  NaN  4.0
3  NaN  3.0  NaN

In [33]:
data.fillna(12)

0     1     2     3
0   1.0   2.0   3.0  12.0
1  12.0  12.0  12.0  12.0
2   2.0  12.0   4.0  12.0
3  12.0   3.0  12.0  12.0

In [34]:
s = Series([10,20,30,40])
s

0    10
1    20
2    30
3    40
dtype: int64

In [35]:
s1 = Series(np.arange(10), index=[['a','a','b','b','b','c','c','d','e','e'],[1,2,1,2,3,1,2,1,1,2]])
s1

a  1    0
   2    1
b  1    2
   2    3
   3    4
c  1    5
   2    6
d  1    7
e  1    8
   2    9
dtype: int64

In [36]:
s1[‘b’][3]

SyntaxError: invalid character '‘' (U+2018) (3196312590.py, line 1)

In [37]:
s1['b'][3]

4

In [38]:
s1['b'][2]

3

In [39]:
s1['e'][2]

9

In [40]:
s1.index

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('b', 3),
            ('c', 1),
            ('c', 2),
            ('d', 1),
            ('e', 1),
            ('e', 2)],
           )

In [41]:
s1['b']

1    2
2    3
3    4
dtype: int64

In [42]:
s1['a':'b']

a  1    0
   2    1
b  1    2
   2    3
   3    4
dtype: int64

In [43]:
s1.unstack()

1    2    3
a  0.0  1.0  NaN
b  2.0  3.0  4.0
c  5.0  6.0  NaN
d  7.0  NaN  NaN
e  8.0  9.0  NaN

In [44]:
data_frame = DataFrame(np.arange(15).reshape(5,3),index=['a','b','c','d','e'])

In [45]:
data_frame

0   1   2
a   0   1   2
b   3   4   5
c   6   7   8
d   9  10  11
e  12  13  14

In [46]:
data_frame.stack()

a  0     0
   1     1
   2     2
b  0     3
   1     4
   2     5
c  0     6
   1     7
   2     8
d  0     9
   1    10
   2    11
e  0    12
   1    13
   2    14
dtype: int64

In [48]:
s = Series(data=['laptop','phone','computer','tablet'],index=[1,2,3,4])
s

0      laptop
1       phone
2    computer
3      tablet
dtype: object

In [52]:
import pandas as pd
fruit_prices = pd.read_csv('fruit_prices.csv',usecols=[1,2])
fruit_prices

Fruit  RetailPrice
0                       Apples       1.5193
1           Apples, applesauce       1.0660
2       Apples, ready-to-drink       0.7804
3   Apples, frozen concentrate       0.5853
4                     Apricots       2.9665
..                         ...          ...
57                 Raspberries       6.6391
58                 Raspberries       4.1877
59                Strawberries       2.5800
60                Strawberries       2.8189
61                  Watermelon       0.3604

[62 rows x 2 columns]

In [53]:
dtype(fruit_prices)

NameError: name 'dtype' is not defined

In [54]:
type(fruit_prices)

pandas.core.frame.DataFrame

In [58]:
fruit_prices = pd.read_csv('fruit_prices.csv',usecols=['Fruit']).squeeze("columns")

In [61]:
fruit_prices

0                         Apples
1             Apples, applesauce
2         Apples, ready-to-drink
3     Apples, frozen concentrate
4                       Apricots
                 ...            
57                   Raspberries
58                   Raspberries
59                  Strawberries
60                  Strawberries
61                    Watermelon
Name: Fruit, Length: 62, dtype: object

In [62]:
fruit_retailprice = pd.read_csv('fruit_prices.csv',usecols=['RetailPrice']).squeeze("columns")
fruit_retailprice

0     1.5193
1     1.0660
2     0.7804
3     0.5853
4     2.9665
       ...  
57    6.6391
58    4.1877
59    2.5800
60    2.8189
61    0.3604
Name: RetailPrice, Length: 62, dtype: float64

In [1]:
import pandas as pd

In [2]:
import numpy as np
from pandas import DataFrame, Series, pd

ImportError: cannot import name 'pd' from 'pandas' (/Users/administrator/.pyenv/versions/3.10.9/lib/python3.10/site-packages/pandas/__init__.py)

In [3]:
import numpy as np
from pandas import DataFrame, Series
Import pandas as pd

SyntaxError: invalid syntax (3314628997.py, line 3)

In [4]:
import pandas as pd

In [5]:
import numpy as np
from pandas import DataFrame, Series
import pandas as pd

In [6]:
list(fruit_retailprice)

NameError: name 'fruit_retailprice' is not defined

In [7]:
fruit_retailprice = pd.read_csv('fruit_prices.csv',usecols=['RetailPrice']).squeeze("columns")
fruit_retailprice

0     1.5193
1     1.0660
2     0.7804
3     0.5853
4     2.9665
       ...  
57    6.6391
58    4.1877
59    2.5800
60    2.8189
61    0.3604
Name: RetailPrice, Length: 62, dtype: float64

In [8]:
list(fruit_retailprice)

[1.5193,
 1.066,
 0.7804,
 0.5853,
 2.9665,
 1.6905,
 2.06,
 6.6188,
 0.5249,
 3.5585,
 6.0172,
 3.6362,
 4.1739,
 3.3898,
 0.5767,
 3.4269,
 4.5257,
 1.3847,
 4.6513,
 5.5713,
 6.8371,
 1.7198,
 1.5932,
 1.1695,
 1.0415,
 1.8398,
 3.7801,
 0.9215,
 0.7119,
 0.9056,
 2.1849,
 1.1513,
 10.5527,
 1.9062,
 1.2131,
 0.9842,
 0.769,
 1.2904,
 5.5089,
 1.7167,
 2.0237,
 1.8117,
 3.3867,
 1.5865,
 1.9546,
 1.897,
 0.5685,
 1.4344,
 1.4067,
 6.6492,
 1.0288,
 0.6973,
 2.0292,
 5.7042,
 1.5522,
 2.235,
 3.122,
 6.6391,
 4.1877,
 2.58,
 2.8189,
 0.3604]

In [9]:
fruit_prices = pd.read_csv('fruit_prices.csv',usecols=['Fruit']).squeeze("columns")
fruit_prices

0                         Apples
1             Apples, applesauce
2         Apples, ready-to-drink
3     Apples, frozen concentrate
4                       Apricots
                 ...            
57                   Raspberries
58                   Raspberries
59                  Strawberries
60                  Strawberries
61                    Watermelon
Name: Fruit, Length: 62, dtype: object

In [10]:
list(fruit_prices)

['Apples',
 'Apples, applesauce',
 'Apples, ready-to-drink',
 'Apples, frozen concentrate',
 'Apricots',
 'Apricots, packed in juice',
 'Apricots, packed in syrup or water',
 'Apricots',
 'Bananas',
 'Berries, mixed',
 'Blackberries',
 'Blackberries',
 'Blueberries',
 'Blueberries',
 'Cantaloupe',
 'Cherries',
 'Cherries, packed in syrup or water',
 'Clementines',
 'Cranberries',
 'Dates',
 'Figs',
 'Fruit cocktail, packed in juice',
 'Fruit cocktail, packed in syrup or water',
 'Grapefruit',
 'Grapefruit, ready-to-drink',
 'Grapes',
 'Grapes (raisins)',
 'Grapes, ready-to-drink',
 'Grapes, frozen concentrate',
 'Honeydew',
 'Kiwi',
 'Mangoes',
 'Mangoes',
 'Nectarines',
 'Oranges',
 'Oranges, ready-to-drink',
 'Oranges, frozen concentrate',
 'Papaya',
 'Papaya',
 'Peaches',
 'Peaches, packed in juice',
 'Peaches, packed in syrup or water',
 'Peaches',
 'Pears',
 'Pears, packed in juice',
 'Pears, packed in syrup or water',
 'Pineapple',
 'Pineapple, packed in juice',
 'Pineapple, pack

In [11]:
fruit_list = list(fruit_prices)

In [12]:
for fruit in fruit_list:
    print(fruit)

Apples
Apples, applesauce
Apples, ready-to-drink
Apples, frozen concentrate
Apricots
Apricots, packed in juice
Apricots, packed in syrup or water
Apricots
Bananas
Berries, mixed
Blackberries
Blackberries
Blueberries
Blueberries
Cantaloupe
Cherries
Cherries, packed in syrup or water
Clementines
Cranberries
Dates
Figs
Fruit cocktail, packed in juice
Fruit cocktail, packed in syrup or water
Grapefruit
Grapefruit, ready-to-drink
Grapes
Grapes (raisins)
Grapes, ready-to-drink
Grapes, frozen concentrate
Honeydew
Kiwi
Mangoes
Mangoes
Nectarines
Oranges
Oranges, ready-to-drink
Oranges, frozen concentrate
Papaya
Papaya
Peaches
Peaches, packed in juice
Peaches, packed in syrup or water
Peaches
Pears
Pears, packed in juice
Pears, packed in syrup or water
Pineapple
Pineapple, packed in juice
Pineapple, packed in syrup or water
Pineapple
Pineapple, ready-to-drink
Pineapple, frozen concentrate
Plum
Plum (prunes)
Plum (prune), ready-to-drink
Pomegranate
Pomegranate, ready-to-drink
Raspberries
Raspber

In [13]:
fruit_names

NameError: name 'fruit_names' is not defined

In [14]:
fruit_prices

0                         Apples
1             Apples, applesauce
2         Apples, ready-to-drink
3     Apples, frozen concentrate
4                       Apricots
                 ...            
57                   Raspberries
58                   Raspberries
59                  Strawberries
60                  Strawberries
61                    Watermelon
Name: Fruit, Length: 62, dtype: object

In [15]:
dict(fruit_prices)

{0: 'Apples',
 1: 'Apples, applesauce',
 2: 'Apples, ready-to-drink',
 3: 'Apples, frozen concentrate',
 4: 'Apricots',
 5: 'Apricots, packed in juice',
 6: 'Apricots, packed in syrup or water',
 7: 'Apricots',
 8: 'Bananas',
 9: 'Berries, mixed',
 10: 'Blackberries',
 11: 'Blackberries',
 12: 'Blueberries',
 13: 'Blueberries',
 14: 'Cantaloupe',
 15: 'Cherries',
 16: 'Cherries, packed in syrup or water',
 17: 'Clementines',
 18: 'Cranberries',
 19: 'Dates',
 20: 'Figs',
 21: 'Fruit cocktail, packed in juice',
 22: 'Fruit cocktail, packed in syrup or water',
 23: 'Grapefruit',
 24: 'Grapefruit, ready-to-drink',
 25: 'Grapes',
 26: 'Grapes (raisins)',
 27: 'Grapes, ready-to-drink',
 28: 'Grapes, frozen concentrate',
 29: 'Honeydew',
 30: 'Kiwi',
 31: 'Mangoes',
 32: 'Mangoes',
 33: 'Nectarines',
 34: 'Oranges',
 35: 'Oranges, ready-to-drink',
 36: 'Oranges, frozen concentrate',
 37: 'Papaya',
 38: 'Papaya',
 39: 'Peaches',
 40: 'Peaches, packed in juice',
 41: 'Peaches, packed in syrup 

In [16]:
fruit_dictionary = dict(fruit_prices)

In [17]:
fruit_dictionary

{0: 'Apples',
 1: 'Apples, applesauce',
 2: 'Apples, ready-to-drink',
 3: 'Apples, frozen concentrate',
 4: 'Apricots',
 5: 'Apricots, packed in juice',
 6: 'Apricots, packed in syrup or water',
 7: 'Apricots',
 8: 'Bananas',
 9: 'Berries, mixed',
 10: 'Blackberries',
 11: 'Blackberries',
 12: 'Blueberries',
 13: 'Blueberries',
 14: 'Cantaloupe',
 15: 'Cherries',
 16: 'Cherries, packed in syrup or water',
 17: 'Clementines',
 18: 'Cranberries',
 19: 'Dates',
 20: 'Figs',
 21: 'Fruit cocktail, packed in juice',
 22: 'Fruit cocktail, packed in syrup or water',
 23: 'Grapefruit',
 24: 'Grapefruit, ready-to-drink',
 25: 'Grapes',
 26: 'Grapes (raisins)',
 27: 'Grapes, ready-to-drink',
 28: 'Grapes, frozen concentrate',
 29: 'Honeydew',
 30: 'Kiwi',
 31: 'Mangoes',
 32: 'Mangoes',
 33: 'Nectarines',
 34: 'Oranges',
 35: 'Oranges, ready-to-drink',
 36: 'Oranges, frozen concentrate',
 37: 'Papaya',
 38: 'Papaya',
 39: 'Peaches',
 40: 'Peaches, packed in juice',
 41: 'Peaches, packed in syrup 

In [18]:
fruit_dictionary[5]

'Apricots, packed in juice'

In [19]:
type(fruit_prices)

pandas.core.series.Series

In [20]:
type(fruit_dictionary)

dict

In [21]:
sorted(fruit_prices)

['Apples',
 'Apples, applesauce',
 'Apples, frozen concentrate',
 'Apples, ready-to-drink',
 'Apricots',
 'Apricots',
 'Apricots, packed in juice',
 'Apricots, packed in syrup or water',
 'Bananas',
 'Berries, mixed',
 'Blackberries',
 'Blackberries',
 'Blueberries',
 'Blueberries',
 'Cantaloupe',
 'Cherries',
 'Cherries, packed in syrup or water',
 'Clementines',
 'Cranberries',
 'Dates',
 'Figs',
 'Fruit cocktail, packed in juice',
 'Fruit cocktail, packed in syrup or water',
 'Grapefruit',
 'Grapefruit, ready-to-drink',
 'Grapes',
 'Grapes (raisins)',
 'Grapes, frozen concentrate',
 'Grapes, ready-to-drink',
 'Honeydew',
 'Kiwi',
 'Mangoes',
 'Mangoes',
 'Nectarines',
 'Oranges',
 'Oranges, frozen concentrate',
 'Oranges, ready-to-drink',
 'Papaya',
 'Papaya',
 'Peaches',
 'Peaches',
 'Peaches, packed in juice',
 'Peaches, packed in syrup or water',
 'Pears',
 'Pears, packed in juice',
 'Pears, packed in syrup or water',
 'Pineapple',
 'Pineapple',
 'Pineapple, frozen concentrate',


In [22]:
sorted(fruit_retailprice)

[0.3604,
 0.5249,
 0.5685,
 0.5767,
 0.5853,
 0.6973,
 0.7119,
 0.769,
 0.7804,
 0.9056,
 0.9215,
 0.9842,
 1.0288,
 1.0415,
 1.066,
 1.1513,
 1.1695,
 1.2131,
 1.2904,
 1.3847,
 1.4067,
 1.4344,
 1.5193,
 1.5522,
 1.5865,
 1.5932,
 1.6905,
 1.7167,
 1.7198,
 1.8117,
 1.8398,
 1.897,
 1.9062,
 1.9546,
 2.0237,
 2.0292,
 2.06,
 2.1849,
 2.235,
 2.58,
 2.8189,
 2.9665,
 3.122,
 3.3867,
 3.3898,
 3.4269,
 3.5585,
 3.6362,
 3.7801,
 4.1739,
 4.1877,
 4.5257,
 4.6513,
 5.5089,
 5.5713,
 5.7042,
 6.0172,
 6.6188,
 6.6391,
 6.6492,
 6.8371,
 10.5527]

In [25]:
"Apples" in fruit_prices.values

True

In [26]:
s = Series([10,20,30,40], index=['a','b','c','d'])
s

a    10
b    20
c    30
d    40
dtype: int64

In [27]:
s['c']

30

In [28]:
s['a':'c']

a    10
b    20
c    30
dtype: int64

In [29]:
s

a    10
b    20
c    30
d    40
dtype: int64

In [30]:
s[2]

/var/folders/bv/dtkgtzxx4654_5b6ys39vyrh0000gn/T/ipykernel_16898/2635755408.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s[2]


30

In [31]:
s.iloc[2]

30

In [32]:
s

a    10
b    20
c    30
d    40
dtype: int64

In [34]:
s[0:3]

a    10
b    20
c    30
dtype: int64

In [1]:
import numpy as np
from pandas import DataFrame, Series
import pandas as pd

In [2]:
s = Series([10,20,30,40], index=['a','b','c','d'])
s

a    10
b    20
c    30
d    40
dtype: int64

In [3]:
s.iloc[0:3]

a    10
b    20
c    30
dtype: int64

In [5]:
s[s<20]

a    10
dtype: int64

In [6]:
s

a    10
b    20
c    30
d    40
dtype: int64

In [7]:
s[['a','c']]

a    10
c    30
dtype: int64

In [8]:
s[[0,2,3]]

/var/folders/bv/dtkgtzxx4654_5b6ys39vyrh0000gn/T/ipykernel_16226/3564952764.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s[[0,2,3]]


a    10
c    30
d    40
dtype: int64

In [9]:
s.iloc[[0,2,3]]

a    10
c    30
d    40
dtype: int64

In [10]:
fruit_prices

NameError: name 'fruit_prices' is not defined

In [11]:
fruit_prices = pd.read_csv('fruit_prices.csv',usecols=['Fruit']).squeeze("columns")
fruit_prices

0                         Apples
1             Apples, applesauce
2         Apples, ready-to-drink
3     Apples, frozen concentrate
4                       Apricots
                 ...            
57                   Raspberries
58                   Raspberries
59                  Strawberries
60                  Strawberries
61                    Watermelon
Name: Fruit, Length: 62, dtype: object

In [12]:
fruit_dictionary = dict(fruit_prices)
fruit_dictionary

{0: 'Apples',
 1: 'Apples, applesauce',
 2: 'Apples, ready-to-drink',
 3: 'Apples, frozen concentrate',
 4: 'Apricots',
 5: 'Apricots, packed in juice',
 6: 'Apricots, packed in syrup or water',
 7: 'Apricots',
 8: 'Bananas',
 9: 'Berries, mixed',
 10: 'Blackberries',
 11: 'Blackberries',
 12: 'Blueberries',
 13: 'Blueberries',
 14: 'Cantaloupe',
 15: 'Cherries',
 16: 'Cherries, packed in syrup or water',
 17: 'Clementines',
 18: 'Cranberries',
 19: 'Dates',
 20: 'Figs',
 21: 'Fruit cocktail, packed in juice',
 22: 'Fruit cocktail, packed in syrup or water',
 23: 'Grapefruit',
 24: 'Grapefruit, ready-to-drink',
 25: 'Grapes',
 26: 'Grapes (raisins)',
 27: 'Grapes, ready-to-drink',
 28: 'Grapes, frozen concentrate',
 29: 'Honeydew',
 30: 'Kiwi',
 31: 'Mangoes',
 32: 'Mangoes',
 33: 'Nectarines',
 34: 'Oranges',
 35: 'Oranges, ready-to-drink',
 36: 'Oranges, frozen concentrate',
 37: 'Papaya',
 38: 'Papaya',
 39: 'Peaches',
 40: 'Peaches, packed in juice',
 41: 'Peaches, packed in syrup 

In [13]:
fruit_retailprice = pd.read_csv('fruit_prices.csv',usecols=['RetailPrice']).squeeze("columns")
fruit_retailprice

0     1.5193
1     1.0660
2     0.7804
3     0.5853
4     2.9665
       ...  
57    6.6391
58    4.1877
59    2.5800
60    2.8189
61    0.3604
Name: RetailPrice, Length: 62, dtype: float64

In [14]:
fruit_prices[4]

'Apricots'

In [15]:
fruit_prices[[0,1,2,3,4]]

0                        Apples
1            Apples, applesauce
2        Apples, ready-to-drink
3    Apples, frozen concentrate
4                      Apricots
Name: Fruit, dtype: object

In [16]:
fruit_prices[[10:20]]

SyntaxError: invalid syntax (1676399437.py, line 1)

In [18]:
fruit_prices[10:21]

10                          Blackberries
11                          Blackberries
12                           Blueberries
13                           Blueberries
14                            Cantaloupe
15                              Cherries
16    Cherries, packed in syrup or water
17                           Clementines
18                           Cranberries
19                                 Dates
20                                  Figs
Name: Fruit, dtype: object

In [19]:
fruit_prices[0]

'Apples'

In [20]:
fruit_prices.iloc[0]

'Apples'

In [21]:
fruits = Series(['Apple', 'Mango', 'Orange'], index=[1,2,3])
fruits

1     Apple
2     Mango
3    Orange
dtype: object

In [22]:
fruits[1]

'Apple'

In [23]:
fruits.iloc[1]

'Mango'

In [25]:
fruit_prices.iloc[[1,2,3,4]]

1            Apples, applesauce
2        Apples, ready-to-drink
3    Apples, frozen concentrate
4                      Apricots
Name: Fruit, dtype: object

In [27]:
fruit_prices.iloc[:10]

0                                Apples
1                    Apples, applesauce
2                Apples, ready-to-drink
3            Apples, frozen concentrate
4                              Apricots
5             Apricots, packed in juice
6    Apricots, packed in syrup or water
7                              Apricots
8                               Bananas
9                        Berries, mixed
Name: Fruit, dtype: object

In [28]:
fruit_prices.iloc[10]

'Blackberries'

In [29]:
fruit_prices

0                         Apples
1             Apples, applesauce
2         Apples, ready-to-drink
3     Apples, frozen concentrate
4                       Apricots
                 ...            
57                   Raspberries
58                   Raspberries
59                  Strawberries
60                  Strawberries
61                    Watermelon
Name: Fruit, Length: 62, dtype: object

In [30]:
fruit_prices.iloc[100]

IndexError: single positional indexer is out-of-bounds

In [31]:
fruit_prices.get(10)

'Blackberries'

In [32]:
fruit_prices.get(100)

In [33]:
fruit_prices.get(100,"Generic Fruit")

'Generic Fruit'

In [1]:
import numpy as np
from pandas import DataFrame, Series
import pandas as pd

In [2]:
fruit_prices = pd.read_csv('fruit_prices.csv',usecols=['Fruit']).squeeze("columns")
fruit_prices

0                         Apples
1             Apples, applesauce
2         Apples, ready-to-drink
3     Apples, frozen concentrate
4                       Apricots
                 ...            
57                   Raspberries
58                   Raspberries
59                  Strawberries
60                  Strawberries
61                    Watermelon
Name: Fruit, Length: 62, dtype: object

In [3]:
fruit_retailprice = pd.read_csv('fruit_prices.csv',usecols=['RetailPrice']).squeeze("columns")
fruit_retailprice

0     1.5193
1     1.0660
2     0.7804
3     0.5853
4     2.9665
       ...  
57    6.6391
58    4.1877
59    2.5800
60    2.8189
61    0.3604
Name: RetailPrice, Length: 62, dtype: float64

In [4]:
fruit_dictionary = dict(fruit_prices)
fruit_dictionary

{0: 'Apples',
 1: 'Apples, applesauce',
 2: 'Apples, ready-to-drink',
 3: 'Apples, frozen concentrate',
 4: 'Apricots',
 5: 'Apricots, packed in juice',
 6: 'Apricots, packed in syrup or water',
 7: 'Apricots',
 8: 'Bananas',
 9: 'Berries, mixed',
 10: 'Blackberries',
 11: 'Blackberries',
 12: 'Blueberries',
 13: 'Blueberries',
 14: 'Cantaloupe',
 15: 'Cherries',
 16: 'Cherries, packed in syrup or water',
 17: 'Clementines',
 18: 'Cranberries',
 19: 'Dates',
 20: 'Figs',
 21: 'Fruit cocktail, packed in juice',
 22: 'Fruit cocktail, packed in syrup or water',
 23: 'Grapefruit',
 24: 'Grapefruit, ready-to-drink',
 25: 'Grapes',
 26: 'Grapes (raisins)',
 27: 'Grapes, ready-to-drink',
 28: 'Grapes, frozen concentrate',
 29: 'Honeydew',
 30: 'Kiwi',
 31: 'Mangoes',
 32: 'Mangoes',
 33: 'Nectarines',
 34: 'Oranges',
 35: 'Oranges, ready-to-drink',
 36: 'Oranges, frozen concentrate',
 37: 'Papaya',
 38: 'Papaya',
 39: 'Peaches',
 40: 'Peaches, packed in juice',
 41: 'Peaches, packed in syrup 

In [5]:
fruit_prices[0] = "Oranges"

In [6]:
fruit_prices

0                        Oranges
1             Apples, applesauce
2         Apples, ready-to-drink
3     Apples, frozen concentrate
4                       Apricots
                 ...            
57                   Raspberries
58                   Raspberries
59                  Strawberries
60                  Strawberries
61                    Watermelon
Name: Fruit, Length: 62, dtype: object

In [7]:
fruit_prices[0] = "Apples"

In [8]:
fruit_prices

0                         Apples
1             Apples, applesauce
2         Apples, ready-to-drink
3     Apples, frozen concentrate
4                       Apricots
                 ...            
57                   Raspberries
58                   Raspberries
59                  Strawberries
60                  Strawberries
61                    Watermelon
Name: Fruit, Length: 62, dtype: object

In [9]:
fruit_prices.iloc[0] = "Oranges"
fruit_prices

0                        Oranges
1             Apples, applesauce
2         Apples, ready-to-drink
3     Apples, frozen concentrate
4                       Apricots
                 ...            
57                   Raspberries
58                   Raspberries
59                  Strawberries
60                  Strawberries
61                    Watermelon
Name: Fruit, Length: 62, dtype: object

In [10]:
fruit_prices.iloc[[1,2,3]] = ["Peaches","Pineapples","Watermelons"]
fruit_prices

0          Oranges
1          Peaches
2       Pineapples
3      Watermelons
4         Apricots
          ...     
57     Raspberries
58     Raspberries
59    Strawberries
60    Strawberries
61      Watermelon
Name: Fruit, Length: 62, dtype: object

In [11]:
fruit_prices.iloc[[0,1,2,3]] = ["Apples","Apples, applesauce","Apples, ready-to-drink","Apples, frozen concentrate"]
fruit_prices

0                         Apples
1             Apples, applesauce
2         Apples, ready-to-drink
3     Apples, frozen concentrate
4                       Apricots
                 ...            
57                   Raspberries
58                   Raspberries
59                  Strawberries
60                  Strawberries
61                    Watermelon
Name: Fruit, Length: 62, dtype: object

In [12]:
s = pd.Series([10,20,30,40], index=['apple','banana','cherry','date'])
s

apple     10
banana    20
cherry    30
date      40
dtype: int64

In [14]:
s.loc['banana'] = 200
s

apple      10
banana    200
cherry     30
date       40
dtype: int64

In [15]:
s.loc[['apple','cherry',]] = [1,3]
s

apple       1
banana    200
cherry      3
date       40
dtype: int64

In [16]:
s

apple       1
banana    200
cherry      3
date       40
dtype: int64

In [17]:
s.loc['banana':'date'] = [25,35,45]
s

apple      1
banana    25
cherry    35
date      45
dtype: int64

In [1]:
import numpy as np
from pandas import DataFrame, Series
import pandas as pd

In [2]:
fruit_prices = pd.read_csv('fruit_prices.csv',usecols=['Fruit']).squeeze("columns")
fruit_prices

0                         Apples
1             Apples, applesauce
2         Apples, ready-to-drink
3     Apples, frozen concentrate
4                       Apricots
                 ...            
57                   Raspberries
58                   Raspberries
59                  Strawberries
60                  Strawberries
61                    Watermelon
Name: Fruit, Length: 62, dtype: object

In [3]:
fruit_retailprice = pd.read_csv('fruit_prices.csv',usecols=['RetailPrice']).squeeze("columns")
fruit_retailprice

0     1.5193
1     1.0660
2     0.7804
3     0.5853
4     2.9665
       ...  
57    6.6391
58    4.1877
59    2.5800
60    2.8189
61    0.3604
Name: RetailPrice, Length: 62, dtype: float64

In [4]:
fruit_dictionary = dict(fruit_prices)
fruit_dictionary

{0: 'Apples',
 1: 'Apples, applesauce',
 2: 'Apples, ready-to-drink',
 3: 'Apples, frozen concentrate',
 4: 'Apricots',
 5: 'Apricots, packed in juice',
 6: 'Apricots, packed in syrup or water',
 7: 'Apricots',
 8: 'Bananas',
 9: 'Berries, mixed',
 10: 'Blackberries',
 11: 'Blackberries',
 12: 'Blueberries',
 13: 'Blueberries',
 14: 'Cantaloupe',
 15: 'Cherries',
 16: 'Cherries, packed in syrup or water',
 17: 'Clementines',
 18: 'Cranberries',
 19: 'Dates',
 20: 'Figs',
 21: 'Fruit cocktail, packed in juice',
 22: 'Fruit cocktail, packed in syrup or water',
 23: 'Grapefruit',
 24: 'Grapefruit, ready-to-drink',
 25: 'Grapes',
 26: 'Grapes (raisins)',
 27: 'Grapes, ready-to-drink',
 28: 'Grapes, frozen concentrate',
 29: 'Honeydew',
 30: 'Kiwi',
 31: 'Mangoes',
 32: 'Mangoes',
 33: 'Nectarines',
 34: 'Oranges',
 35: 'Oranges, ready-to-drink',
 36: 'Oranges, frozen concentrate',
 37: 'Papaya',
 38: 'Papaya',
 39: 'Peaches',
 40: 'Peaches, packed in juice',
 41: 'Peaches, packed in syrup 

In [5]:
s = pd.Series([10,20,30,40], index=['apple','banana','cherry','date'])
s

apple     10
banana    20
cherry    30
date      40
dtype: int64

In [6]:
s.loc['banana'] = 200
s

apple      10
banana    200
cherry     30
date       40
dtype: int64

In [7]:
s.loc[['apple','cherry',]] = [1,3]
s

apple       1
banana    200
cherry      3
date       40
dtype: int64

In [8]:
s.loc['banana':'date'] = [25,35,45]
s

apple      1
banana    25
cherry    35
date      45
dtype: int64

In [9]:
fruit_prices

0                         Apples
1             Apples, applesauce
2         Apples, ready-to-drink
3     Apples, frozen concentrate
4                       Apricots
                 ...            
57                   Raspberries
58                   Raspberries
59                  Strawberries
60                  Strawberries
61                    Watermelon
Name: Fruit, Length: 62, dtype: object

In [10]:
fruit_prices.value_counts()

Fruit
Papaya                                      2
Blackberries                                2
Mangoes                                     2
Peaches                                     2
Blueberries                                 2
Pineapple                                   2
Apricots                                    2
Raspberries                                 2
Strawberries                                2
Oranges, ready-to-drink                     1
Oranges, frozen concentrate                 1
Pears, packed in juice                      1
Oranges                                     1
Peaches, packed in juice                    1
Peaches, packed in syrup or water           1
Pears                                       1
Apples                                      1
Pineapple, packed in syrup or water         1
Pears, packed in syrup or water             1
Pineapple, packed in juice                  1
Pineapple, ready-to-drink                   1
Pineapple, frozen concentrat

In [11]:
fruit_prices.value_counts(sort=False)

Fruit
Apples                                      1
Apples, applesauce                          1
Apples, ready-to-drink                      1
Apples, frozen concentrate                  1
Apricots                                    2
Apricots, packed in juice                   1
Apricots, packed in syrup or water          1
Bananas                                     1
Berries, mixed                              1
Blackberries                                2
Blueberries                                 2
Cantaloupe                                  1
Cherries                                    1
Cherries, packed in syrup or water          1
Clementines                                 1
Cranberries                                 1
Dates                                       1
Figs                                        1
Fruit cocktail, packed in juice             1
Fruit cocktail, packed in syrup or water    1
Grapefruit                                  1
Grapefruit, ready-to-drink  

In [12]:
fruit_prices.value_counts(ascending=True)

Fruit
Apples                                      1
Grapes, frozen concentrate                  1
Kiwi                                        1
Nectarines                                  1
Oranges                                     1
Oranges, ready-to-drink                     1
Oranges, frozen concentrate                 1
Peaches, packed in juice                    1
Peaches, packed in syrup or water           1
Pears                                       1
Grapes, ready-to-drink                      1
Pears, packed in juice                      1
Pineapple, packed in juice                  1
Pineapple, packed in syrup or water         1
Pineapple, ready-to-drink                   1
Pineapple, frozen concentrate               1
Plum                                        1
Plum (prunes)                               1
Plum (prune), ready-to-drink                1
Pomegranate                                 1
Pomegranate, ready-to-drink                 1
Pears, packed in syrup or wa

In [13]:
fruit_prices.value_counts(normalize=True)

Fruit
Papaya                                      0.032258
Blackberries                                0.032258
Mangoes                                     0.032258
Peaches                                     0.032258
Blueberries                                 0.032258
Pineapple                                   0.032258
Apricots                                    0.032258
Raspberries                                 0.032258
Strawberries                                0.032258
Oranges, ready-to-drink                     0.016129
Oranges, frozen concentrate                 0.016129
Pears, packed in juice                      0.016129
Oranges                                     0.016129
Peaches, packed in juice                    0.016129
Peaches, packed in syrup or water           0.016129
Pears                                       0.016129
Apples                                      0.016129
Pineapple, packed in syrup or water         0.016129
Pears, packed in syrup or water         

In [1]:
import numpy as np
from pandas import DataFrame, Series
import pandas as pd

In [2]:
fruit_prices = pd.read_csv('fruit_prices.csv',usecols=['Fruit']).squeeze("columns")
fruit_prices

0                         Apples
1             Apples, applesauce
2         Apples, ready-to-drink
3     Apples, frozen concentrate
4                       Apricots
                 ...            
57                   Raspberries
58                   Raspberries
59                  Strawberries
60                  Strawberries
61                    Watermelon
Name: Fruit, Length: 62, dtype: object

In [3]:
fruit_retailprice = pd.read_csv('fruit_prices.csv',usecols=['RetailPrice']).squeeze("columns")
fruit_retailprice

0     1.5193
1     1.0660
2     0.7804
3     0.5853
4     2.9665
       ...  
57    6.6391
58    4.1877
59    2.5800
60    2.8189
61    0.3604
Name: RetailPrice, Length: 62, dtype: float64

In [4]:
fruit_dictionary = dict(fruit_prices)
fruit_dictionary

{0: 'Apples',
 1: 'Apples, applesauce',
 2: 'Apples, ready-to-drink',
 3: 'Apples, frozen concentrate',
 4: 'Apricots',
 5: 'Apricots, packed in juice',
 6: 'Apricots, packed in syrup or water',
 7: 'Apricots',
 8: 'Bananas',
 9: 'Berries, mixed',
 10: 'Blackberries',
 11: 'Blackberries',
 12: 'Blueberries',
 13: 'Blueberries',
 14: 'Cantaloupe',
 15: 'Cherries',
 16: 'Cherries, packed in syrup or water',
 17: 'Clementines',
 18: 'Cranberries',
 19: 'Dates',
 20: 'Figs',
 21: 'Fruit cocktail, packed in juice',
 22: 'Fruit cocktail, packed in syrup or water',
 23: 'Grapefruit',
 24: 'Grapefruit, ready-to-drink',
 25: 'Grapes',
 26: 'Grapes (raisins)',
 27: 'Grapes, ready-to-drink',
 28: 'Grapes, frozen concentrate',
 29: 'Honeydew',
 30: 'Kiwi',
 31: 'Mangoes',
 32: 'Mangoes',
 33: 'Nectarines',
 34: 'Oranges',
 35: 'Oranges, ready-to-drink',
 36: 'Oranges, frozen concentrate',
 37: 'Papaya',
 38: 'Papaya',
 39: 'Peaches',
 40: 'Peaches, packed in juice',
 41: 'Peaches, packed in syrup 

In [5]:
s = pd.Series([10,20,30,40], index=['apple','banana','cherry','date'])
s

apple     10
banana    20
cherry    30
date      40
dtype: int64

In [6]:
prices = [100,200,300,400,500]
prices_series = pd.Series(prices)

In [7]:
prices_series

0    100
1    200
2    300
3    400
4    500
dtype: int64

In [8]:
def summer_discount(x):
    return x - (x*0.1)    

In [9]:
prices_series.apply(summer_discount)

0     90.0
1    180.0
2    270.0
3    360.0
4    450.0
dtype: float64

In [13]:
scores = pd.Series([56,78,91,34,98,23,43,59])
def pass_or_fail(num):
    if num > 35:
        return "You passed!"
    else:
        return "Fail"
result = scores.apply(pass_or_fail)
result

0    You passed!
1    You passed!
2    You passed!
3           Fail
4    You passed!
5           Fail
6    You passed!
7    You passed!
dtype: object

In [14]:
result.value_counts()

You passed!    6
Fail           2
Name: count, dtype: int64

In [15]:
result.value_counts(normalize=True)

You passed!    0.75
Fail           0.25
Name: proportion, dtype: float64

In [16]:
fruit_prices

0                         Apples
1             Apples, applesauce
2         Apples, ready-to-drink
3     Apples, frozen concentrate
4                       Apricots
                 ...            
57                   Raspberries
58                   Raspberries
59                  Strawberries
60                  Strawberries
61                    Watermelon
Name: Fruit, Length: 62, dtype: object

In [17]:
fruit_prices.apply(len)

0      6
1     18
2     22
3     26
4      8
      ..
57    11
58    11
59    12
60    12
61    10
Name: Fruit, Length: 62, dtype: int64

In [1]:
import numpy as np
from pandas import DataFrame, Series
import pandas as pd

In [3]:
fruit_names = pd.read_csv('fruit_prices.csv',usecols=['Fruit']).squeeze("columns")
fruit_names

0                         Apples
1             Apples, applesauce
2         Apples, ready-to-drink
3     Apples, frozen concentrate
4                       Apricots
                 ...            
57                   Raspberries
58                   Raspberries
59                  Strawberries
60                  Strawberries
61                    Watermelon
Name: Fruit, Length: 62, dtype: object

In [4]:
fruit_retailprice = pd.read_csv('fruit_prices.csv',usecols=['RetailPrice']).squeeze("columns")
fruit_retailprice

0     1.5193
1     1.0660
2     0.7804
3     0.5853
4     2.9665
       ...  
57    6.6391
58    4.1877
59    2.5800
60    2.8189
61    0.3604
Name: RetailPrice, Length: 62, dtype: float64

In [5]:
fruit_prices = pd.read_csv('fruit_prices.csv',usecols=['Fruit']).squeeze("columns")
fruit_prices

0                         Apples
1             Apples, applesauce
2         Apples, ready-to-drink
3     Apples, frozen concentrate
4                       Apricots
                 ...            
57                   Raspberries
58                   Raspberries
59                  Strawberries
60                  Strawberries
61                    Watermelon
Name: Fruit, Length: 62, dtype: object

In [6]:
fruit_dictionary = dict(fruit_prices)
fruit_dictionary

{0: 'Apples',
 1: 'Apples, applesauce',
 2: 'Apples, ready-to-drink',
 3: 'Apples, frozen concentrate',
 4: 'Apricots',
 5: 'Apricots, packed in juice',
 6: 'Apricots, packed in syrup or water',
 7: 'Apricots',
 8: 'Bananas',
 9: 'Berries, mixed',
 10: 'Blackberries',
 11: 'Blackberries',
 12: 'Blueberries',
 13: 'Blueberries',
 14: 'Cantaloupe',
 15: 'Cherries',
 16: 'Cherries, packed in syrup or water',
 17: 'Clementines',
 18: 'Cranberries',
 19: 'Dates',
 20: 'Figs',
 21: 'Fruit cocktail, packed in juice',
 22: 'Fruit cocktail, packed in syrup or water',
 23: 'Grapefruit',
 24: 'Grapefruit, ready-to-drink',
 25: 'Grapes',
 26: 'Grapes (raisins)',
 27: 'Grapes, ready-to-drink',
 28: 'Grapes, frozen concentrate',
 29: 'Honeydew',
 30: 'Kiwi',
 31: 'Mangoes',
 32: 'Mangoes',
 33: 'Nectarines',
 34: 'Oranges',
 35: 'Oranges, ready-to-drink',
 36: 'Oranges, frozen concentrate',
 37: 'Papaya',
 38: 'Papaya',
 39: 'Peaches',
 40: 'Peaches, packed in juice',
 41: 'Peaches, packed in syrup 

In [7]:
s = pd.Series([10,20,30,40], index=['apple','banana','cherry','date'])
s

apple     10
banana    20
cherry    30
date      40
dtype: int64

In [8]:
import numpy as np
from pandas import DataFrame, Series
import pandas as pd

In [9]:
s

apple     10
banana    20
cherry    30
date      40
dtype: int64

In [10]:
prices = [100,200,300,400,500]
prices_series = pd.Series(prices)
prices_series

0    100
1    200
2    300
3    400
4    500
dtype: int64

In [12]:
def summer_discount(x):
    return x - (x*0.1)  
prices_series.apply(summer_discount)

0     90.0
1    180.0
2    270.0
3    360.0
4    450.0
dtype: float64

In [13]:
scores = pd.Series([56,78,91,34,98,23,43,59])
def pass_or_fail(num):
    if num > 35:
        return "You passed!"
    else:
        return "Fail"
result = scores.apply(pass_or_fail)
result

0    You passed!
1    You passed!
2    You passed!
3           Fail
4    You passed!
5           Fail
6    You passed!
7    You passed!
dtype: object

In [14]:
fruit_prices.apply(len)

0      6
1     18
2     22
3     26
4      8
      ..
57    11
58    11
59    12
60    12
61    10
Name: Fruit, Length: 62, dtype: int64

In [15]:
stock_symbols = {"Acme Corp":"ACMC","Anton Computers":"ANT", "Maximo Construction":"MCX"}
stock_prices = {"ACMC":29,"MCX":15,"ANT":48}
symbol_series = Series(stock_symbols)
prices_series = Series(stock_prices)
symbol_series

Acme Corp              ACMC
Anton Computers         ANT
Maximo Construction     MCX
dtype: object

In [16]:
prices_series

ACMC    29
MCX     15
ANT     48
dtype: int64

In [17]:
symbol_series.map(prices_series)

Acme Corp              29
Anton Computers        48
Maximo Construction    15
dtype: int64

In [20]:
data = pd.read_csv('data_cleaned_2021.csv')
data

index                                          Job Title  \
0        0                                     Data Scientist   
1        1                          Healthcare Data Scientist   
2        2                                     Data Scientist   
3        3                                     Data Scientist   
4        4                                     Data Scientist   
..     ...                                                ...   
737    950           Sr Scientist, Immuno-Oncology - Oncology   
738    951                               Senior Data Engineer   
739    952  Project Scientist - Auton Lab, Robotics Institute   
740    953                               Data Science Manager   
741    955          Research Scientist – Security and Privacy   

                 Salary Estimate  \
0     $53K-$91K (Glassdoor est.)   
1    $63K-$112K (Glassdoor est.)   
2     $80K-$90K (Glassdoor est.)   
3     $56K-$97K (Glassdoor est.)   
4    $86K-$143K (Glassdoor est.)   
..                           ...   
737  $58K-$111K (Glassdoor est.)   
738  $72K-$133K (Glassdoor est.)   
739   $56K-$91K (Glassdoor est.)   
740  $95K-$160K (Glassdoor est.)   
741  $61K-$126K (Glassdoor est.)   

                                       Job Description  Rating  \
0    Data Scientist\nLocation: Albuquerque, NM\nEdu...     3.8   
1    What You Will Do:\n\nI. General Summary\n\nThe...     3.4   
2    KnowBe4, Inc. is a high growth information sec...     4.8   
3    *Organization and Job ID**\nJob ID: 310709\n\n...     3.8   
4    Data Scientist\nAffinity Solutions / Marketing...     2.9   
..                                                 ...     ...   
737  Site Name: USA - Massachusetts - Cambridge\nPo...     3.9   
738  THE CHALLENGE\nEventbrite has a world-class da...     4.4   
739  The Auton Lab at Carnegie Mellon University is...     2.6   
740  Data Science ManagerResponsibilities:\n\nOvers...     3.2   
741  Returning Candidate? Log back in to the Career...     3.6   

                                   Company Name         Location  \
0                        Tecolote Research\n3.8  Albuquerque, NM   
1    University of Maryland Medical System\n3.4    Linthicum, MD   
2                                  KnowBe4\n4.8   Clearwater, FL   
3                                     PNNL\n3.8     Richland, WA   
4                       Affinity Solutions\n2.9     New York, NY   
..                                          ...              ...   
737                                    GSK\n3.9    Cambridge, MA   
738                             Eventbrite\n4.4    Nashville, TN   
739         Software Engineering Institute\n2.6   Pittsburgh, PA   
740                           Numeric, LLC\n3.2    Allentown, PA   
741           Riverside Research Institute\n3.6  Beavercreek, OH   

                  Headquarters          Size  Founded  ... tensor hadoop  \
0                   Goleta, CA   501 - 1000      1973  ...      0      0   
1                Baltimore, MD       10000+      1984  ...      0      0   
2               Clearwater, FL   501 - 1000      2010  ...      0      0   
3                 Richland, WA  1001 - 5000      1965  ...      0      0   
4                 New York, NY     51 - 200      1998  ...      0      0   
..                         ...           ...      ...  ...    ...    ...   
737  Brentford, United Kingdom       10000+      1830  ...      0      0   
738          San Francisco, CA  1001 - 5000      2006  ...      0      1   
739             Pittsburgh, PA   501 - 1000      1984  ...      0      0   
740            Chadds Ford, PA       1 - 50        -1  ...      0      0   
741              Arlington, VA   501 - 1000      1967  ...      0      0   

    tableau bi flink  mongo  google_an    job_title_sim  seniority_by_title  \
0         1  1     0      0          0   data scientist                  na   
1         0  0     0      0          0   data scientist                  na   
2         0  0     0      0    

In [23]:
data = data.set_index('index')

In [24]:
data

Job Title  \
index                                                      
0                                         Data Scientist   
1                              Healthcare Data Scientist   
2                                         Data Scientist   
3                                         Data Scientist   
4                                         Data Scientist   
...                                                  ...   
950             Sr Scientist, Immuno-Oncology - Oncology   
951                                 Senior Data Engineer   
952    Project Scientist - Auton Lab, Robotics Institute   
953                                 Data Science Manager   
955            Research Scientist – Security and Privacy   

                   Salary Estimate  \
index                                
0       $53K-$91K (Glassdoor est.)   
1      $63K-$112K (Glassdoor est.)   
2       $80K-$90K (Glassdoor est.)   
3       $56K-$97K (Glassdoor est.)   
4      $86K-$143K (Glassdoor est.)   
...                            ...   
950    $58K-$111K (Glassdoor est.)   
951    $72K-$133K (Glassdoor est.)   
952     $56K-$91K (Glassdoor est.)   
953    $95K-$160K (Glassdoor est.)   
955    $61K-$126K (Glassdoor est.)   

                                         Job Description  Rating  \
index                                                              
0      Data Scientist\nLocation: Albuquerque, NM\nEdu...     3.8   
1      What You Will Do:\n\nI. General Summary\n\nThe...     3.4   
2      KnowBe4, Inc. is a high growth information sec...     4.8   
3      *Organization and Job ID**\nJob ID: 310709\n\n...     3.8   
4      Data Scientist\nAffinity Solutions / Marketing...     2.9   
...                                                  ...     ...   
950    Site Name: USA - Massachusetts - Cambridge\nPo...     3.9   
951    THE CHALLENGE\nEventbrite has a world-class da...     4.4   
952    The Auton Lab at Carnegie Mellon University is...     2.6   
953    Data Science ManagerResponsibilities:\n\nOvers...     3.2   
955    Returning Candidate? Log back in to the Career...     3.6   

                                     Company Name         Location  \
index                                                                
0                          Tecolote Research\n3.8  Albuquerque, NM   
1      University of Maryland Medical System\n3.4    Linthicum, MD   
2                                    KnowBe4\n4.8   Clearwater, FL   
3                                       PNNL\n3.8     Richland, WA   
4                         Affinity Solutions\n2.9     New York, NY   
...                                           ...              ...   
950                                      GSK\n3.9    Cambridge, MA   
951                               Eventbrite\n4.4    Nashville, TN   
952           Software Engineering Institute\n2.6   Pittsburgh, PA   
953                             Numeric, LLC\n3.2    Allentown, PA   
955             Riverside Research Institute\n3.6  Beavercreek, OH   

                    Headquarters          Size  Founded  \
index                                                     
0                     Goleta, CA   501 - 1000      1973   
1                  Baltimore, MD       10000+      1984   
2                 Clearwater, FL   501 - 1000      2010   
3                   Richland, WA  1001 - 5000      1965   
4                   New York, NY     51 - 200      1998   
...                          ...           ...      ...   
950    Brentford, United Kingdom       10000+      1830   
951            San Francisco, CA  1001 - 5000      2006   
952               Pittsburgh, PA   501 - 1000      1984   
953              Chadds Ford, PA       1 - 50        -1   
955                Arlington, VA   501 - 1000      1967   

            Type of ownership  ... tensor hadoop tableau bi  flink  mongo  \
index                          ...                                          
0           Company - Private  ...      0      0     

In [25]:
data.index.name="Job ID"

In [26]:
data

Job Title  \
Job ID                                                      
0                                          Data Scientist   
1                               Healthcare Data Scientist   
2                                          Data Scientist   
3                                          Data Scientist   
4                                          Data Scientist   
...                                                   ...   
950              Sr Scientist, Immuno-Oncology - Oncology   
951                                  Senior Data Engineer   
952     Project Scientist - Auton Lab, Robotics Institute   
953                                  Data Science Manager   
955             Research Scientist – Security and Privacy   

                    Salary Estimate  \
Job ID                                
0        $53K-$91K (Glassdoor est.)   
1       $63K-$112K (Glassdoor est.)   
2        $80K-$90K (Glassdoor est.)   
3        $56K-$97K (Glassdoor est.)   
4       $86K-$143K (Glassdoor est.)   
...                             ...   
950     $58K-$111K (Glassdoor est.)   
951     $72K-$133K (Glassdoor est.)   
952      $56K-$91K (Glassdoor est.)   
953     $95K-$160K (Glassdoor est.)   
955     $61K-$126K (Glassdoor est.)   

                                          Job Description  Rating  \
Job ID                                                              
0       Data Scientist\nLocation: Albuquerque, NM\nEdu...     3.8   
1       What You Will Do:\n\nI. General Summary\n\nThe...     3.4   
2       KnowBe4, Inc. is a high growth information sec...     4.8   
3       *Organization and Job ID**\nJob ID: 310709\n\n...     3.8   
4       Data Scientist\nAffinity Solutions / Marketing...     2.9   
...                                                   ...     ...   
950     Site Name: USA - Massachusetts - Cambridge\nPo...     3.9   
951     THE CHALLENGE\nEventbrite has a world-class da...     4.4   
952     The Auton Lab at Carnegie Mellon University is...     2.6   
953     Data Science ManagerResponsibilities:\n\nOvers...     3.2   
955     Returning Candidate? Log back in to the Career...     3.6   

                                      Company Name         Location  \
Job ID                                                                
0                           Tecolote Research\n3.8  Albuquerque, NM   
1       University of Maryland Medical System\n3.4    Linthicum, MD   
2                                     KnowBe4\n4.8   Clearwater, FL   
3                                        PNNL\n3.8     Richland, WA   
4                          Affinity Solutions\n2.9     New York, NY   
...                                            ...              ...   
950                                       GSK\n3.9    Cambridge, MA   
951                                Eventbrite\n4.4    Nashville, TN   
952            Software Engineering Institute\n2.6   Pittsburgh, PA   
953                              Numeric, LLC\n3.2    Allentown, PA   
955              Riverside Research Institute\n3.6  Beavercreek, OH   

                     Headquarters          Size  Founded  \
Job ID                                                     
0                      Goleta, CA   501 - 1000      1973   
1                   Baltimore, MD       10000+      1984   
2                  Clearwater, FL   501 - 1000      2010   
3                    Richland, WA  1001 - 5000      1965   
4                    New York, NY     51 - 200      1998   
...                           ...           ...      ...   
950     Brentford, United Kingdom       10000+      1830   
951             San Francisco, CA  1001 - 5000      2006   
952                Pittsburgh, PA   501 - 1000      1984   
953               Chadds Ford, PA       1 - 50        -1   
955                 Arlington, VA   501 - 1000      1967   

             Type of ownership  ... tensor hadoop tableau bi  flink  mongo  \
Job ID                          ...                              

In [1]:
import numpy as np
from pandas import DataFrame, Series
import pandas as pd

In [2]:
stock_symbols = {"Acme Corp":"ACMC","Anton Computers":"ANT", "Maximo Construction":"MCX"}
stock_prices = {"ACMC":29,"MCX":15,"ANT":48}
symbol_series = Series(stock_symbols)
prices_series = Series(stock_prices)
symbol_series

Acme Corp              ACMC
Anton Computers         ANT
Maximo Construction     MCX
dtype: object

In [3]:
symbol_series.map(prices_series)

Acme Corp              29
Anton Computers        48
Maximo Construction    15
dtype: int64

In [4]:
data = pd.read_csv('data_cleaned_2021.csv')
data

index                                          Job Title  \
0        0                                     Data Scientist   
1        1                          Healthcare Data Scientist   
2        2                                     Data Scientist   
3        3                                     Data Scientist   
4        4                                     Data Scientist   
..     ...                                                ...   
737    950           Sr Scientist, Immuno-Oncology - Oncology   
738    951                               Senior Data Engineer   
739    952  Project Scientist - Auton Lab, Robotics Institute   
740    953                               Data Science Manager   
741    955          Research Scientist – Security and Privacy   

                 Salary Estimate  \
0     $53K-$91K (Glassdoor est.)   
1    $63K-$112K (Glassdoor est.)   
2     $80K-$90K (Glassdoor est.)   
3     $56K-$97K (Glassdoor est.)   
4    $86K-$143K (Glassdoor est.)   
..                           ...   
737  $58K-$111K (Glassdoor est.)   
738  $72K-$133K (Glassdoor est.)   
739   $56K-$91K (Glassdoor est.)   
740  $95K-$160K (Glassdoor est.)   
741  $61K-$126K (Glassdoor est.)   

                                       Job Description  Rating  \
0    Data Scientist\nLocation: Albuquerque, NM\nEdu...     3.8   
1    What You Will Do:\n\nI. General Summary\n\nThe...     3.4   
2    KnowBe4, Inc. is a high growth information sec...     4.8   
3    *Organization and Job ID**\nJob ID: 310709\n\n...     3.8   
4    Data Scientist\nAffinity Solutions / Marketing...     2.9   
..                                                 ...     ...   
737  Site Name: USA - Massachusetts - Cambridge\nPo...     3.9   
738  THE CHALLENGE\nEventbrite has a world-class da...     4.4   
739  The Auton Lab at Carnegie Mellon University is...     2.6   
740  Data Science ManagerResponsibilities:\n\nOvers...     3.2   
741  Returning Candidate? Log back in to the Career...     3.6   

                                   Company Name         Location  \
0                        Tecolote Research\n3.8  Albuquerque, NM   
1    University of Maryland Medical System\n3.4    Linthicum, MD   
2                                  KnowBe4\n4.8   Clearwater, FL   
3                                     PNNL\n3.8     Richland, WA   
4                       Affinity Solutions\n2.9     New York, NY   
..                                          ...              ...   
737                                    GSK\n3.9    Cambridge, MA   
738                             Eventbrite\n4.4    Nashville, TN   
739         Software Engineering Institute\n2.6   Pittsburgh, PA   
740                           Numeric, LLC\n3.2    Allentown, PA   
741           Riverside Research Institute\n3.6  Beavercreek, OH   

                  Headquarters          Size  Founded  ... tensor hadoop  \
0                   Goleta, CA   501 - 1000      1973  ...      0      0   
1                Baltimore, MD       10000+      1984  ...      0      0   
2               Clearwater, FL   501 - 1000      2010  ...      0      0   
3                 Richland, WA  1001 - 5000      1965  ...      0      0   
4                 New York, NY     51 - 200      1998  ...      0      0   
..                         ...           ...      ...  ...    ...    ...   
737  Brentford, United Kingdom       10000+      1830  ...      0      0   
738          San Francisco, CA  1001 - 5000      2006  ...      0      1   
739             Pittsburgh, PA   501 - 1000      1984  ...      0      0   
740            Chadds Ford, PA       1 - 50        -1  ...      0      0   
741              Arlington, VA   501 - 1000      1967  ...      0      0   

    tableau bi flink  mongo  google_an    job_title_sim  seniority_by_title  \
0         1  1     0      0          0   data scientist                  na   
1         0  0     0      0          0   data scientist                  na   
2         0  0     0      0    

In [5]:
data.index.name="Job ID"
data

index                                          Job Title  \
Job ID                                                             
0           0                                     Data Scientist   
1           1                          Healthcare Data Scientist   
2           2                                     Data Scientist   
3           3                                     Data Scientist   
4           4                                     Data Scientist   
...       ...                                                ...   
737       950           Sr Scientist, Immuno-Oncology - Oncology   
738       951                               Senior Data Engineer   
739       952  Project Scientist - Auton Lab, Robotics Institute   
740       953                               Data Science Manager   
741       955          Research Scientist – Security and Privacy   

                    Salary Estimate  \
Job ID                                
0        $53K-$91K (Glassdoor est.)   
1       $63K-$112K (Glassdoor est.)   
2        $80K-$90K (Glassdoor est.)   
3        $56K-$97K (Glassdoor est.)   
4       $86K-$143K (Glassdoor est.)   
...                             ...   
737     $58K-$111K (Glassdoor est.)   
738     $72K-$133K (Glassdoor est.)   
739      $56K-$91K (Glassdoor est.)   
740     $95K-$160K (Glassdoor est.)   
741     $61K-$126K (Glassdoor est.)   

                                          Job Description  Rating  \
Job ID                                                              
0       Data Scientist\nLocation: Albuquerque, NM\nEdu...     3.8   
1       What You Will Do:\n\nI. General Summary\n\nThe...     3.4   
2       KnowBe4, Inc. is a high growth information sec...     4.8   
3       *Organization and Job ID**\nJob ID: 310709\n\n...     3.8   
4       Data Scientist\nAffinity Solutions / Marketing...     2.9   
...                                                   ...     ...   
737     Site Name: USA - Massachusetts - Cambridge\nPo...     3.9   
738     THE CHALLENGE\nEventbrite has a world-class da...     4.4   
739     The Auton Lab at Carnegie Mellon University is...     2.6   
740     Data Science ManagerResponsibilities:\n\nOvers...     3.2   
741     Returning Candidate? Log back in to the Career...     3.6   

                                      Company Name         Location  \
Job ID                                                                
0                           Tecolote Research\n3.8  Albuquerque, NM   
1       University of Maryland Medical System\n3.4    Linthicum, MD   
2                                     KnowBe4\n4.8   Clearwater, FL   
3                                        PNNL\n3.8     Richland, WA   
4                          Affinity Solutions\n2.9     New York, NY   
...                                            ...              ...   
737                                       GSK\n3.9    Cambridge, MA   
738                                Eventbrite\n4.4    Nashville, TN   
739            Software Engineering Institute\n2.6   Pittsburgh, PA   
740                              Numeric, LLC\n3.2    Allentown, PA   
741              Riverside Research Institute\n3.6  Beavercreek, OH   

                     Headquarters          Size  Founded  ... tensor hadoop  \
Job ID                                                    ...                 
0                      Goleta, CA   501 - 1000      1973  ...      0      0   
1                   Baltimore, MD       10000+      1984  ...      0      0   
2                  Clearwater, FL   501 - 1000      2010  ...      0      0   
3                    Richland, WA  1001 - 5000      1965  ...      0      0   
4                    New York, NY     51 - 200      1998  ...      0      0   
...                           ...           ...      ...  ...    ...    ...   
737     Brentford, United Kingdom       10000+      1830  ...      0      0   
738             San Francisco, CA  1001 - 5000      2006  ...      0      1   
739

In [1]:
import numpy as np
from pandas import DataFrame, Series
import pandas as pd

In [2]:
stock_symbols = {"Acme Corp":"ACMC","Anton Computers":"ANT", "Maximo Construction":"MCX"}
stock_prices = {"ACMC":29,"MCX":15,"ANT":48}
symbol_series = Series(stock_symbols)
prices_series = Series(stock_prices)
symbol_series

Acme Corp              ACMC
Anton Computers         ANT
Maximo Construction     MCX
dtype: object

In [3]:
prices_series

ACMC    29
MCX     15
ANT     48
dtype: int64

In [4]:
symbol_series.map(prices_series)

Acme Corp              29
Anton Computers        48
Maximo Construction    15
dtype: int64

In [5]:
data = pd.read_csv('data_cleaned_2021.csv')
data

index                                          Job Title  \
0        0                                     Data Scientist   
1        1                          Healthcare Data Scientist   
2        2                                     Data Scientist   
3        3                                     Data Scientist   
4        4                                     Data Scientist   
..     ...                                                ...   
737    950           Sr Scientist, Immuno-Oncology - Oncology   
738    951                               Senior Data Engineer   
739    952  Project Scientist - Auton Lab, Robotics Institute   
740    953                               Data Science Manager   
741    955          Research Scientist – Security and Privacy   

                 Salary Estimate  \
0     $53K-$91K (Glassdoor est.)   
1    $63K-$112K (Glassdoor est.)   
2     $80K-$90K (Glassdoor est.)   
3     $56K-$97K (Glassdoor est.)   
4    $86K-$143K (Glassdoor est.)   
..                           ...   
737  $58K-$111K (Glassdoor est.)   
738  $72K-$133K (Glassdoor est.)   
739   $56K-$91K (Glassdoor est.)   
740  $95K-$160K (Glassdoor est.)   
741  $61K-$126K (Glassdoor est.)   

                                       Job Description  Rating  \
0    Data Scientist\nLocation: Albuquerque, NM\nEdu...     3.8   
1    What You Will Do:\n\nI. General Summary\n\nThe...     3.4   
2    KnowBe4, Inc. is a high growth information sec...     4.8   
3    *Organization and Job ID**\nJob ID: 310709\n\n...     3.8   
4    Data Scientist\nAffinity Solutions / Marketing...     2.9   
..                                                 ...     ...   
737  Site Name: USA - Massachusetts - Cambridge\nPo...     3.9   
738  THE CHALLENGE\nEventbrite has a world-class da...     4.4   
739  The Auton Lab at Carnegie Mellon University is...     2.6   
740  Data Science ManagerResponsibilities:\n\nOvers...     3.2   
741  Returning Candidate? Log back in to the Career...     3.6   

                                   Company Name         Location  \
0                        Tecolote Research\n3.8  Albuquerque, NM   
1    University of Maryland Medical System\n3.4    Linthicum, MD   
2                                  KnowBe4\n4.8   Clearwater, FL   
3                                     PNNL\n3.8     Richland, WA   
4                       Affinity Solutions\n2.9     New York, NY   
..                                          ...              ...   
737                                    GSK\n3.9    Cambridge, MA   
738                             Eventbrite\n4.4    Nashville, TN   
739         Software Engineering Institute\n2.6   Pittsburgh, PA   
740                           Numeric, LLC\n3.2    Allentown, PA   
741           Riverside Research Institute\n3.6  Beavercreek, OH   

                  Headquarters          Size  Founded  ... tensor hadoop  \
0                   Goleta, CA   501 - 1000      1973  ...      0      0   
1                Baltimore, MD       10000+      1984  ...      0      0   
2               Clearwater, FL   501 - 1000      2010  ...      0      0   
3                 Richland, WA  1001 - 5000      1965  ...      0      0   
4                 New York, NY     51 - 200      1998  ...      0      0   
..                         ...           ...      ...  ...    ...    ...   
737  Brentford, United Kingdom       10000+      1830  ...      0      0   
738          San Francisco, CA  1001 - 5000      2006  ...      0      1   
739             Pittsburgh, PA   501 - 1000      1984  ...      0      0   
740            Chadds Ford, PA       1 - 50        -1  ...      0      0   
741              Arlington, VA   501 - 1000      1967  ...      0      0   

    tableau bi flink  mongo  google_an    job_title_sim  seniority_by_title  \
0         1  1     0      0          0   data scientist                  na   
1         0  0     0      0          0   data scientist                  na   
2         0  0     0      0    

In [6]:
data.index.name="Job ID"
data

index                                          Job Title  \
Job ID                                                             
0           0                                     Data Scientist   
1           1                          Healthcare Data Scientist   
2           2                                     Data Scientist   
3           3                                     Data Scientist   
4           4                                     Data Scientist   
...       ...                                                ...   
737       950           Sr Scientist, Immuno-Oncology - Oncology   
738       951                               Senior Data Engineer   
739       952  Project Scientist - Auton Lab, Robotics Institute   
740       953                               Data Science Manager   
741       955          Research Scientist – Security and Privacy   

                    Salary Estimate  \
Job ID                                
0        $53K-$91K (Glassdoor est.)   
1       $63K-$112K (Glassdoor est.)   
2        $80K-$90K (Glassdoor est.)   
3        $56K-$97K (Glassdoor est.)   
4       $86K-$143K (Glassdoor est.)   
...                             ...   
737     $58K-$111K (Glassdoor est.)   
738     $72K-$133K (Glassdoor est.)   
739      $56K-$91K (Glassdoor est.)   
740     $95K-$160K (Glassdoor est.)   
741     $61K-$126K (Glassdoor est.)   

                                          Job Description  Rating  \
Job ID                                                              
0       Data Scientist\nLocation: Albuquerque, NM\nEdu...     3.8   
1       What You Will Do:\n\nI. General Summary\n\nThe...     3.4   
2       KnowBe4, Inc. is a high growth information sec...     4.8   
3       *Organization and Job ID**\nJob ID: 310709\n\n...     3.8   
4       Data Scientist\nAffinity Solutions / Marketing...     2.9   
...                                                   ...     ...   
737     Site Name: USA - Massachusetts - Cambridge\nPo...     3.9   
738     THE CHALLENGE\nEventbrite has a world-class da...     4.4   
739     The Auton Lab at Carnegie Mellon University is...     2.6   
740     Data Science ManagerResponsibilities:\n\nOvers...     3.2   
741     Returning Candidate? Log back in to the Career...     3.6   

                                      Company Name         Location  \
Job ID                                                                
0                           Tecolote Research\n3.8  Albuquerque, NM   
1       University of Maryland Medical System\n3.4    Linthicum, MD   
2                                     KnowBe4\n4.8   Clearwater, FL   
3                                        PNNL\n3.8     Richland, WA   
4                          Affinity Solutions\n2.9     New York, NY   
...                                            ...              ...   
737                                       GSK\n3.9    Cambridge, MA   
738                                Eventbrite\n4.4    Nashville, TN   
739            Software Engineering Institute\n2.6   Pittsburgh, PA   
740                              Numeric, LLC\n3.2    Allentown, PA   
741              Riverside Research Institute\n3.6  Beavercreek, OH   

                     Headquarters          Size  Founded  ... tensor hadoop  \
Job ID                                                    ...                 
0                      Goleta, CA   501 - 1000      1973  ...      0      0   
1                   Baltimore, MD       10000+      1984  ...      0      0   
2                  Clearwater, FL   501 - 1000      2010  ...      0      0   
3                    Richland, WA  1001 - 5000      1965  ...      0      0   
4                    New York, NY     51 - 200      1998  ...      0      0   
...                           ...           ...      ...  ...    ...    ...   
737     Brentford, United Kingdom       10000+      1830  ...      0      0   
738             San Francisco, CA  1001 - 5000      2006  ...      0      1   
739

In [7]:
data.head(10)

index                  Job Title               Salary Estimate  \
Job ID                                                                   
0           0             Data Scientist    $53K-$91K (Glassdoor est.)   
1           1  Healthcare Data Scientist   $63K-$112K (Glassdoor est.)   
2           2             Data Scientist    $80K-$90K (Glassdoor est.)   
3           3             Data Scientist    $56K-$97K (Glassdoor est.)   
4           4             Data Scientist   $86K-$143K (Glassdoor est.)   
5           5             Data Scientist   $71K-$119K (Glassdoor est.)   
6           6             Data Scientist    $54K-$93K (Glassdoor est.)   
7           7             Data Scientist   $86K-$142K (Glassdoor est.)   
8           8         Research Scientist    $38K-$84K (Glassdoor est.)   
9           9             Data Scientist  $120K-$160K (Glassdoor est.)   

                                          Job Description  Rating  \
Job ID                                                              
0       Data Scientist\nLocation: Albuquerque, NM\nEdu...     3.8   
1       What You Will Do:\n\nI. General Summary\n\nThe...     3.4   
2       KnowBe4, Inc. is a high growth information sec...     4.8   
3       *Organization and Job ID**\nJob ID: 310709\n\n...     3.8   
4       Data Scientist\nAffinity Solutions / Marketing...     2.9   
5       CyrusOne is seeking a talented Data Scientist ...     3.4   
6       Job Description\n\n**Please only local candida...     4.1   
7       Advanced Analytics – Lead Data Scientist\nOver...     3.8   
8       SUMMARY\n\nThe Research Scientist I will be ta...     3.3   
9       isn’t your usual company. Our work is powered ...     4.6   

                                      Company Name         Location  \
Job ID                                                                
0                           Tecolote Research\n3.8  Albuquerque, NM   
1       University of Maryland Medical System\n3.4    Linthicum, MD   
2                                     KnowBe4\n4.8   Clearwater, FL   
3                                        PNNL\n3.8     Richland, WA   
4                          Affinity Solutions\n2.9     New York, NY   
5                                    CyrusOne\n3.4       Dallas, TX   
6                          ClearOne Advantage\n4.1    Baltimore, MD   
7                                  Logic20/20\n3.8     San Jose, CA   
8                   Rochester Regional Health\n3.3    Rochester, NY   
9                                    <intent>\n4.6     New York, NY   

          Headquarters          Size  Founded  ... tensor hadoop tableau bi  \
Job ID                                         ...                            
0           Goleta, CA   501 - 1000      1973  ...      0      0       1  1   
1        Baltimore, MD       10000+      1984  ...      0      0       0  0   
2       Clearwater, FL   501 - 1000      2010  ...      0      0       0  0   
3         Richland, WA  1001 - 5000      1965  ...      0      0       0  0   
4         New York, NY     51 - 200      1998  ...      0      0       0  0   
5           Dallas, TX    201 - 500      2000  ...      0      0       0  1   
6        Baltimore, MD   501 - 1000      2008  ...      0      0       0  0   
7          Seattle, WA    201 - 500      2005  ...      1      0       0  0   
8        Rochester, NY       10000+      2014  ...      0      0       0  0   
9         New York, NY     51 - 200      2009  ...      0      0       0  0   

       flink  mongo  google_an    job_title_sim  seniority_by_title  Degree  
Job ID                                                                       
0          0      0          0   data scientist                  na       M  
1          0      0          0   data scientist                  na       M  
2          0      0          0   data scientist                  na       M  
3          0      0          0   data scientist                  na      na  
4          0      0 

In [8]:
data.tail()

index                                          Job Title  \
Job ID                                                             
737       950           Sr Scientist, Immuno-Oncology - Oncology   
738       951                               Senior Data Engineer   
739       952  Project Scientist - Auton Lab, Robotics Institute   
740       953                               Data Science Manager   
741       955          Research Scientist – Security and Privacy   

                    Salary Estimate  \
Job ID                                
737     $58K-$111K (Glassdoor est.)   
738     $72K-$133K (Glassdoor est.)   
739      $56K-$91K (Glassdoor est.)   
740     $95K-$160K (Glassdoor est.)   
741     $61K-$126K (Glassdoor est.)   

                                          Job Description  Rating  \
Job ID                                                              
737     Site Name: USA - Massachusetts - Cambridge\nPo...     3.9   
738     THE CHALLENGE\nEventbrite has a world-class da...     4.4   
739     The Auton Lab at Carnegie Mellon University is...     2.6   
740     Data Science ManagerResponsibilities:\n\nOvers...     3.2   
741     Returning Candidate? Log back in to the Career...     3.6   

                               Company Name         Location  \
Job ID                                                         
737                                GSK\n3.9    Cambridge, MA   
738                         Eventbrite\n4.4    Nashville, TN   
739     Software Engineering Institute\n2.6   Pittsburgh, PA   
740                       Numeric, LLC\n3.2    Allentown, PA   
741       Riverside Research Institute\n3.6  Beavercreek, OH   

                     Headquarters          Size  Founded  ... tensor hadoop  \
Job ID                                                    ...                 
737     Brentford, United Kingdom       10000+      1830  ...      0      0   
738             San Francisco, CA  1001 - 5000      2006  ...      0      1   
739                Pittsburgh, PA   501 - 1000      1984  ...      0      0   
740               Chadds Ford, PA       1 - 50        -1  ...      0      0   
741                 Arlington, VA   501 - 1000      1967  ...      0      0   

       tableau bi flink  mongo  google_an    job_title_sim  \
Job ID                                                       
737          0  0     0      0          0  other scientist   
738          0  0     0      0          0    data engineer   
739          0  0     0      0          0  other scientist   
740          0  0     0      0          0   data scientist   
741          0  0     0      0          0  other scientist   

        seniority_by_title  Degree  
Job ID                              
737                     sr       M  
738                     sr      na  
739                     na       P  
740                     na      na  
741                     na       M  

[5 rows x 42 columns]

In [1]:
import numpy as np
from pandas import DataFrame, Series
import pandas as pd

In [2]:
stock_symbols = {"Acme Corp":"ACMC","Anton Computers":"ANT", "Maximo Construction":"MCX"}
stock_prices = {"ACMC":29,"MCX":15,"ANT":48}
symbol_series = Series(stock_symbols)
prices_series = Series(stock_prices)
symbol_series

Acme Corp              ACMC
Anton Computers         ANT
Maximo Construction     MCX
dtype: object

In [3]:
prices_series

ACMC    29
MCX     15
ANT     48
dtype: int64

In [4]:
symbol_series.map(prices_series)

Acme Corp              29
Anton Computers        48
Maximo Construction    15
dtype: int64

In [5]:
data = pd.read_csv('data_cleaned_2021.csv')
data

index                                          Job Title  \
0        0                                     Data Scientist   
1        1                          Healthcare Data Scientist   
2        2                                     Data Scientist   
3        3                                     Data Scientist   
4        4                                     Data Scientist   
..     ...                                                ...   
737    950           Sr Scientist, Immuno-Oncology - Oncology   
738    951                               Senior Data Engineer   
739    952  Project Scientist - Auton Lab, Robotics Institute   
740    953                               Data Science Manager   
741    955          Research Scientist – Security and Privacy   

                 Salary Estimate  \
0     $53K-$91K (Glassdoor est.)   
1    $63K-$112K (Glassdoor est.)   
2     $80K-$90K (Glassdoor est.)   
3     $56K-$97K (Glassdoor est.)   
4    $86K-$143K (Glassdoor est.)   
..                           ...   
737  $58K-$111K (Glassdoor est.)   
738  $72K-$133K (Glassdoor est.)   
739   $56K-$91K (Glassdoor est.)   
740  $95K-$160K (Glassdoor est.)   
741  $61K-$126K (Glassdoor est.)   

                                       Job Description  Rating  \
0    Data Scientist\nLocation: Albuquerque, NM\nEdu...     3.8   
1    What You Will Do:\n\nI. General Summary\n\nThe...     3.4   
2    KnowBe4, Inc. is a high growth information sec...     4.8   
3    *Organization and Job ID**\nJob ID: 310709\n\n...     3.8   
4    Data Scientist\nAffinity Solutions / Marketing...     2.9   
..                                                 ...     ...   
737  Site Name: USA - Massachusetts - Cambridge\nPo...     3.9   
738  THE CHALLENGE\nEventbrite has a world-class da...     4.4   
739  The Auton Lab at Carnegie Mellon University is...     2.6   
740  Data Science ManagerResponsibilities:\n\nOvers...     3.2   
741  Returning Candidate? Log back in to the Career...     3.6   

                                   Company Name         Location  \
0                        Tecolote Research\n3.8  Albuquerque, NM   
1    University of Maryland Medical System\n3.4    Linthicum, MD   
2                                  KnowBe4\n4.8   Clearwater, FL   
3                                     PNNL\n3.8     Richland, WA   
4                       Affinity Solutions\n2.9     New York, NY   
..                                          ...              ...   
737                                    GSK\n3.9    Cambridge, MA   
738                             Eventbrite\n4.4    Nashville, TN   
739         Software Engineering Institute\n2.6   Pittsburgh, PA   
740                           Numeric, LLC\n3.2    Allentown, PA   
741           Riverside Research Institute\n3.6  Beavercreek, OH   

                  Headquarters          Size  Founded  ... tensor hadoop  \
0                   Goleta, CA   501 - 1000      1973  ...      0      0   
1                Baltimore, MD       10000+      1984  ...      0      0   
2               Clearwater, FL   501 - 1000      2010  ...      0      0   
3                 Richland, WA  1001 - 5000      1965  ...      0      0   
4                 New York, NY     51 - 200      1998  ...      0      0   
..                         ...           ...      ...  ...    ...    ...   
737  Brentford, United Kingdom       10000+      1830  ...      0      0   
738          San Francisco, CA  1001 - 5000      2006  ...      0      1   
739             Pittsburgh, PA   501 - 1000      1984  ...      0      0   
740            Chadds Ford, PA       1 - 50        -1  ...      0      0   
741              Arlington, VA   501 - 1000      1967  ...      0      0   

    tableau bi flink  mongo  google_an    job_title_sim  seniority_by_title  \
0         1  1     0      0          0   data scientist                  na   
1         0  0     0      0          0   data scientist                  na   
2         0  0     0      0    

In [6]:
data.index.name="Job ID"
data

index                                          Job Title  \
Job ID                                                             
0           0                                     Data Scientist   
1           1                          Healthcare Data Scientist   
2           2                                     Data Scientist   
3           3                                     Data Scientist   
4           4                                     Data Scientist   
...       ...                                                ...   
737       950           Sr Scientist, Immuno-Oncology - Oncology   
738       951                               Senior Data Engineer   
739       952  Project Scientist - Auton Lab, Robotics Institute   
740       953                               Data Science Manager   
741       955          Research Scientist – Security and Privacy   

                    Salary Estimate  \
Job ID                                
0        $53K-$91K (Glassdoor est.)   
1       $63K-$112K (Glassdoor est.)   
2        $80K-$90K (Glassdoor est.)   
3        $56K-$97K (Glassdoor est.)   
4       $86K-$143K (Glassdoor est.)   
...                             ...   
737     $58K-$111K (Glassdoor est.)   
738     $72K-$133K (Glassdoor est.)   
739      $56K-$91K (Glassdoor est.)   
740     $95K-$160K (Glassdoor est.)   
741     $61K-$126K (Glassdoor est.)   

                                          Job Description  Rating  \
Job ID                                                              
0       Data Scientist\nLocation: Albuquerque, NM\nEdu...     3.8   
1       What You Will Do:\n\nI. General Summary\n\nThe...     3.4   
2       KnowBe4, Inc. is a high growth information sec...     4.8   
3       *Organization and Job ID**\nJob ID: 310709\n\n...     3.8   
4       Data Scientist\nAffinity Solutions / Marketing...     2.9   
...                                                   ...     ...   
737     Site Name: USA - Massachusetts - Cambridge\nPo...     3.9   
738     THE CHALLENGE\nEventbrite has a world-class da...     4.4   
739     The Auton Lab at Carnegie Mellon University is...     2.6   
740     Data Science ManagerResponsibilities:\n\nOvers...     3.2   
741     Returning Candidate? Log back in to the Career...     3.6   

                                      Company Name         Location  \
Job ID                                                                
0                           Tecolote Research\n3.8  Albuquerque, NM   
1       University of Maryland Medical System\n3.4    Linthicum, MD   
2                                     KnowBe4\n4.8   Clearwater, FL   
3                                        PNNL\n3.8     Richland, WA   
4                          Affinity Solutions\n2.9     New York, NY   
...                                            ...              ...   
737                                       GSK\n3.9    Cambridge, MA   
738                                Eventbrite\n4.4    Nashville, TN   
739            Software Engineering Institute\n2.6   Pittsburgh, PA   
740                              Numeric, LLC\n3.2    Allentown, PA   
741              Riverside Research Institute\n3.6  Beavercreek, OH   

                     Headquarters          Size  Founded  ... tensor hadoop  \
Job ID                                                    ...                 
0                      Goleta, CA   501 - 1000      1973  ...      0      0   
1                   Baltimore, MD       10000+      1984  ...      0      0   
2                  Clearwater, FL   501 - 1000      2010  ...      0      0   
3                    Richland, WA  1001 - 5000      1965  ...      0      0   
4                    New York, NY     51 - 200      1998  ...      0      0   
...                           ...           ...      ...  ...    ...    ...   
737     Brentford, United Kingdom       10000+      1830  ...      0      0   
738             San Francisco, CA  1001 - 5000      2006  ...      0      1   
739

In [7]:
data.index

RangeIndex(start=0, stop=742, step=1, name='Job ID')

In [8]:
data.values

array([[0, 'Data Scientist', '$53K-$91K (Glassdoor est.)', ...,
        'data scientist', 'na', 'M'],
       [1, 'Healthcare Data Scientist', '$63K-$112K (Glassdoor est.)',
        ..., 'data scientist', 'na', 'M'],
       [2, 'Data Scientist', '$80K-$90K (Glassdoor est.)', ...,
        'data scientist', 'na', 'M'],
       ...,
       [952, 'Project Scientist - Auton Lab, Robotics Institute',
        '$56K-$91K (Glassdoor est.)', ..., 'other scientist', 'na', 'P'],
       [953, 'Data Science Manager', '$95K-$160K (Glassdoor est.)', ...,
        'data scientist', 'na', 'na'],
       [955, 'Research Scientist – Security and Privacy',
        '$61K-$126K (Glassdoor est.)', ..., 'other scientist', 'na', 'M']],
      dtype=object)

In [9]:
data.shape

(742, 42)